In [1]:
#import pysr
import pandas as pd
import os
from pysr import PySRRegressor,TensorBoardLoggerSpec
import sympy
import numpy as np
import itertools
import random
import ast
import re
import warnings
warnings.filterwarnings("ignore")

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

In [22]:

# create dataframes 
dir = "datasets/Feynman/Feynman_with_units"
df_dict={}
mean=0
gamma = 0.01 # changed from 0.001
for file in os.listdir(dir):
    if file in ['I.15.10.txt', 'I.48.20.txt', 'II.11.7.txt']:
        continue # these dont have a corresponding entry in the metadata file for some reason...
    fname = os.fsdecode(file)   
    df = pd.read_csv(os.path.join(dir,fname),sep=" ",header=None,engine='pyarrow') # switching engine to pyarrow sped up loading by nearly 6x
    df.dropna(axis=0,how='any',inplace=True,ignore_index=True)
    # add noise to the target variable as described by the paper Symbolic Regression with a Learned Concept Library
    std = gamma*np.sqrt((1/df.shape[0])*np.sum((df.iloc[:,-1:])**2))
    noise_array = np.random.normal(mean, std, size=df.shape[0])
    df.iloc[:,-1] = df.iloc[:,-1] + noise_array
    dfname,_ = os.path.splitext(fname)
    df_dict[dfname] = df

print("DFs created")
file="best_equations.csv",  

c=0

DFs created

In [23]:
class ConvertMinus(ast.NodeTransformer): # convert -sin(x) to 0-sin(x) 
    def visit_UnaryOp(self,node):
        self.generic_visit(node)
        if isinstance(node.op,ast.USub):
            return ast.BinOp(left=ast.Constant(value=0),op=ast.Sub(),right=node.operand)
    
        return node

In [24]:
from pydantic import BaseModel,Field,field_validator
import typing

class ResponseStructure(BaseModel):
    expressions:typing.List[str] = Field(...,min_length=1,max_length=1,description="A list of expressions generated by the model")
    
    @field_validator("expressions",mode='before')
    @classmethod
    # for when the model does not listen and writes an equation instead of an expression
    def remove_equals(cls, v):
        if isinstance(v, list):
            cleaned_expressions = []
            for expr in v:
                if isinstance(expr, str) and '=' in expr:
                    clean_expr = expr.split('=', 1)[-1].strip()
                    cleaned_expressions.append(clean_expr)
                else:
                    cleaned_expressions.append(expr)
            return cleaned_expressions
        return v
        
    
    @field_validator("expressions")
    @classmethod
    def check_equations(cls,expr_list):
        clean_list=[]
        for expr in expr_list:
            test_expr = expr.replace("^", "**") # temporarily replace ^ with ** for validatoin purposes
            try:
                tree=ast.parse(test_expr,mode='eval')
                tree=ConvertMinus().visit(tree)
                clean_expr = ast.unparse(tree).replace("**", "^")
                clean_list.append(clean_expr)
            except SyntaxError as e:
                raise ValueError(f"Syntax error in expression '{expr}': {e}")
        return clean_list
        
schema = ResponseStructure.model_json_schema()

In [25]:
df_meta = pd.read_csv('datasets/Feynman/FeynmanEquations.csv') # get the number of variables, the variable names 
df_units = pd.read_csv('datasets/Feynman/units.csv')
units=['m','s','kg','T','V']
def make_unit_string(row):
    parts=[]
    for base in units:
        power=row[base]
        if pd.isna(power) or power==0:
            continue
        if power==1:
            parts.append(f"{base}")
        else:
            parts.append(f"{base}^{int(power)}")
    return ' * '.join(parts) if parts else ""
            
df_units['dimensionality']= df_units.apply(make_unit_string,axis=1)     
    
unit_map = df_units.set_index('Variable')[['dimensionality', 'Units']].to_dict(orient='index')
print(unit_map)

{'A': {'dimensionality': 'm^2', 'Units': 'Area'}, 'a': {'dimensionality': 'm * s^-2', 'Units': 'Acceleration'}, 'A_vec': {'dimensionality': 'm^-1 * s * V', 'Units': 'Vector potential'}, 'alpha': {'dimensionality': '', 'Units': 'Dimensionless'}, 'B': {'dimensionality': 'm^-2 * s * V', 'Units': 'Magnetic field'}, 'beta': {'dimensionality': '', 'Units': 'Dimensionless'}, 'Bx': {'dimensionality': 'm^-2 * s * V', 'Units': 'Magnetic field'}, 'By': {'dimensionality': 'm^-2 * s * V', 'Units': 'Magnetic field'}, 'Bz': {'dimensionality': 'm^-2 * s * V', 'Units': 'Magnetic field'}, 'c': {'dimensionality': 'm * s^-1', 'Units': 'Velocity'}, 'C': {'dimensionality': 'm^2 * s^-2 * kg * V^-2', 'Units': 'Capacitance'}, 'chi': {'dimensionality': '', 'Units': 'Dimensionless'}, 'd': {'dimensionality': 'm', 'Units': 'Length'}, 'D': {'dimensionality': 'm^2 * s^-1', 'Units': 'Diffusion coefficient'}, 'd1': {'dimensionality': 'm', 'Units': 'Length'}, 'd2': {'dimensionality': 'm', 'Units': 'Length'}, 'delta': {'dimensionality': '', 'Units': 'Dimensionless'}, 'el_ct': {'dimensionality': 'm^-1 * s^2 * kg^-1 * V^2', 'Units': '1/(4*pi*epsilon)'}, 'E_n': {'dimensionality': 'm^2 * s^-2 * kg', 'Units': 'Energy'}, 'E_den': {'dimensionality': 'm^-1 * s^-2 * kg', 'Units': 'Energy density'}, 'Ef': {'dimensionality': 'm^-1 * V', 'Units': 'Electric field'}, 'epsilon': {'dimensionality': 'm * s^-2 * kg * V^-2', 'Units': 'Electric permitivity'}, 'f': {'dimensionality': '', 'Units': 'Dimensionless'}, 'F': {'dimensionality': 'm * s^-2 * kg', 'Units': 'Force'}, 'flux': {'dimensionality': 's^-3 * kg', 'Units': 'Energy flux'}, 'foc': {'dimensionality': 'm', 'Units': 'Length'}, 'G': {'dimensionality': 'm^3 * s^-2 * kg^-1', 'Units': "Newton's constant"}, 'g': {'dimensionality': 'm * s^-2', 'Units': 'Acceleration'}, 'g_': {'dimensionality': '', 'Units': 'Dimensionless'}, 'gamma': {'dimensionality': '', 'Units': 'Dimensionless'}, 'H': {'dimensionality': 'm^-2 * s * V', 'Units': 'Magnetic field'}, 'h': {'dimensionality': 'm^2 * s^-1 * kg', 'Units': 'Angular momentum'}, 'hbar': {'dimensionality': 'm^2 * s^-1 * kg', 'Units': 'Angular momentum'}, 'H_G': {'dimensionality': 's^-1', 'Units': 'Hubble constant'}, 'I': {'dimensionality': 'm^2 * s^-3 * kg * V^-1', 'Units': 'Current Intensity'}, 'I_0': {'dimensionality': 'm^2 * s^-3 * kg * V^-1', 'Units': 'Current Intensity'}, 'I1': {'dimensionality': 's^-3 * kg', 'Units': 'Light intensity'}, 'I2': {'dimensionality': 's^-3 * kg', 'Units': 'Light intensity'}, 'Int': {'dimensionality': 's^-3 * kg', 'Units': 'Light intensity'}, 'Int_0': {'dimensionality': 's^-3 * kg', 'Units': 'Light intensity'}, 'j': {'dimensionality': 's^-3 * kg * V^-1', 'Units': 'Current density'}, 'Jz': {'dimensionality': 'm^2 * s^-1 * kg', 'Units': 'Angular momentum'}, 'K': {'dimensionality': 'm^2 * s^-2 * kg', 'Units': 'Energy'}, 'k': {'dimensionality': 'm^-1', 'Units': 'Wave number'}, 'k_f': {'dimensionality': '', 'Units': 'Dimensionless'}, 'k_G': {'dimensionality': 'm^3 * s^-2 * kg', 'Units': 'Gravitational coupling (Gm1m2)'}, 'k_spring': {'dimensionality': 's^-2 * kg', 'Units': 'Spring constant'}, 'kappa': {'dimensionality': 'm * s^-3 * kg * T^-1', 'Units': 'Thermal conductivity'}, 'kb': {'dimensionality': 'm^2 * s^-2 * kg * T^-1', 'Units': 'Boltzmann constant'}, 'L': {'dimensionality': 'm^2 * s^-1 * kg', 'Units': 'Angular momentum'}, 'L_rad': {'dimensionality': 's^-2 * kg', 'Units': 'Spectral radiance'}, 'lambd': {'dimensionality': 'm', 'Units': 'Length'}, 'm': {'dimensionality': 'kg', 'Units': 'Mass'}, 'M': {'dimensionality': 'm * s^-3 * kg * V^-1', 'Units': 'Magnetisation'}, 'm_0': {'dimensionality': 'kg', 'Units': 'Mass'}, 'm1': {'dimensionality': 'kg', 'Units': 'Mass'}, 'm2': {'dimensionality': 'kg', 'Units': 'Mass'}, 'mob': {'dimensionality': 's * kg^-1', 'Units': 'Mobility'}, 'mom': {'dimensionality': 'm^4 * s^-3 * kg * V^-1', 'Units': 'Magnetic moment'}, 'mu': {'dimensionality': '', 'Units': 'Dimensionless'}, 'mu_drift': {'dimensionality': 's^-1 * kg', 'Units': 'Drift velocity constant'}, 'Nn': {'dimensionality': 'm * s^-2 * kg', 'Units': 'Force'}, 'n': {'dimensionality': '', 'Units': 'Dimensionless'}, 'n_rho': {'dimensionality': 'm^-3', 'Units': 'Inverse volume'}, 'n_0': {'dimensionality': '', 'Units': 'Dimensionless'}, 'omega': {'dimensionality': 's^-1', 'Units': 'Frequency'}, 'omega_0': {'dimensionality': 's^-1', 'Units': 'Frequency'}, 'p': {'dimensionality': 'm * s^-1 * kg', 'Units': 'Momentum'}, 'Pol': {'dimensionality': 's^-2 * kg * V^-1', 'Units': 'Polarization'}, 'p_d': {'dimensionality': 'm^3 * s^-2 * kg * V^-1', 'Units': 'Electric dipole moment'}, 'Pwr': {'dimensionality': 'm^2 * s^-3 * kg', 'Units': 'Power'}, 'pr': {'dimensionality': 'm^-1 * s^-2 * kg', 'Units': 'Pressure'}, 'prob': {'dimensionality': '', 'Units': 'Dimensionless'}, 'q': {'dimensionality': 'm^2 * s^-2 * kg * V^-1', 'Units': 'Charge'}, 'q1': {'dimensionality': 'm^2 * s^-2 * kg * V^-1', 'Units': 'Charge'}, 'q2': {'dimensionality': 'm^2 * s^-2 * kg * V^-1', 'Units': 'Charge'}, 'r': {'dimensionality': 'm', 'Units': 'Length'}, 'R': {'dimensionality': 'm^-2 * s^3 * kg^-1 * V^2', 'Units': 'Resistance'}, 'r1': {'dimensionality': 'm', 'Units': 'Length'}, 'r2': {'dimensionality': 'm', 'Units': 'Length'}, 'rho': {'dimensionality': 'm^-3 * kg', 'Units': 'Density'}, 'rho_c': {'dimensionality': 'm^-1 * s^-2 * kg * V^-1', 'Units': 'Volume charge density'}, 'rho_c_0': {'dimensionality': 'm^-1 * s^-2 * kg * V^-1', 'Units': 'Volume charge density'}, 'rho_0': {'dimensionality': 'm^-3 * kg', 'Units': 'Density'}, 'sigma': {'dimensionality': '', 'Units': 'Dimensionless'}, 'sigma_den': {'dimensionality': 's^-2 * kg * V^-1', 'Units': 'Surface Charge density'}, 't': {'dimensionality': 's', 'Units': 'Τime'}, 'T': {'dimensionality': 'T', 'Units': 'Temperature'}, 't1': {'dimensionality': 's', 'Units': 'Τime'}, 'T1': {'dimensionality': 'T', 'Units': 'Temperature'}, 'T2': {'dimensionality': 'T', 'Units': 'Temperature'}, 'tau': {'dimensionality': 'm^2 * s^-2 * kg', 'Units': 'Torque'}, 'theta': {'dimensionality': '', 'Units': 'Dimensionless'}, 'theta1': {'dimensionality': '', 'Units': 'Dimensionless'}, 'theta2': {'dimensionality': '', 'Units': 'Dimensionless'}, 'U': {'dimensionality': 'm^2 * s^-2 * kg', 'Units': 'Energy'}, 'u': {'dimensionality': 'm * s^-1', 'Units': 'Velocity'}, 'v': {'dimensionality': 'm * s^-1', 'Units': 'Velocity'}, 'V': {'dimensionality': 'm^3', 'Units': 'volume'}, 'v1': {'dimensionality': 'm * s^-1', 'Units': 'Velocity'}, 'V1': {'dimensionality': 'm^3', 'Units': 'volume'}, 'V2': {'dimensionality': 'm^3', 'Units': 'volume'}, 'Volt': {'dimensionality': 'V', 'Units': 'Voltage'}, 'w': {'dimensionality': 'm * s^-1', 'Units': 'Velocity'}, 'x': {'dimensionality': 'm', 'Units': 'Length'}, 'x1': {'dimensionality': 'm', 'Units': 'Length'}, 'x2': {'dimensionality': 'm', 'Units': 'Length'}, 'x3': {'dimensionality': 'm', 'Units': 'Length'}, 'y': {'dimensionality': 'm', 'Units': 'Length'}, 'Y': {'dimensionality': 'm^-1 * s^-2 * kg', 'Units': 'Young modulus'}, 'y1': {'dimensionality': 'm', 'Units': 'Length'}, 'y2': {'dimensionality': 'm', 'Units': 'Length'}, 'y3': {'dimensionality': 'm', 'Units': 'Length'}, 'z': {'dimensionality': 'm', 'Units': 'Length'}, 'z1': {'dimensionality': 'm', 'Units': 'Length'}, 'z2': {'dimensionality': 'm', 'Units': 'Length'}, 'mu_S': {'dimensionality': 'm^-1 * s^-2 * kg', 'Units': 'Shear modulus'}, 'L_ind': {'dimensionality': 'm^-2 * s^4 * kg^-1 * V^2', 'Units': 'Inductance'}, 'Z_1': {'dimensionality': '', 'Units': 'Dimensionless'}, 'Z_2': {'dimensionality': '', 'Units': 'Dimensionless'}, nan: {'dimensionality': '', 'Units': nan}}

In [6]:
import sympy as sp
import matplotlib.pyplot as plt
import numpy as np



def get_complexity(tree):
    # this is just the number of nodes in the equation tree by default
    if not tree.args:
        return 1 
    
    return 1 + sum(get_complexity(subtree) for subtree in tree.args)
   
def get_accuracy(equation,X,y_true):
    # equation is the lambda form of an equation
    y_pred = equation(X)
    return np.mean((y_true-y_pred)**2)

def get_string_accuracy(eq_string,X,y_true,variables):
    eq_string = eq_string.replace("^", "**")
    sym_vars = sp.symbols(variables)
    local_dict = {var: sp.Symbol(var) for var in variables}
    expr = sp.sympify(eq_string, locals=local_dict)
    expr_complexity = get_complexity(expr)
    eq = sp.lambdify(sym_vars,expr,modules=['numpy'])
    y_pred = eq(*[X[var] for var in variables])
    return (np.mean((y_true - y_pred)**2),expr_complexity)
    


def get_scores(X,y,equations_df:pd.DataFrame,variables,llm_suggestions):
    # admin work
    
    pysr_stats,llm_stats = get_complexity_accuracy(X,y,equations_df,variables,llm_suggestions)
    # pysr_stats and llm_stats are lists of tuples [(mse,complexity)]
    print(list(map(lambda tup:tup[0],llm_stats)))
    print(list(map(lambda tup:tup[1],llm_stats)))
    llm_df = pd.DataFrame({'sympy_format':llm_suggestions,
                           'mse':[tup[0] for tup in llm_stats],
                           'complexity':[tup[1] for tup in llm_stats],
                           'source':'LLM' })
    
    pysr_df = equations_df[['sympy_format']].copy() 
    pysr_df['mse'] = [tup[0] for tup in pysr_stats]
    pysr_df['complexity'] = [tup[1] for tup in pysr_stats]
    pysr_df['source'] = 'PySR'
    combined_df = pd.concat([pysr_df, llm_df], ignore_index=True)
    # now sort it..
    combined_df = combined_df.sort_values(by='complexity').reset_index(drop=True)
    loss_i = combined_df['mse']
    loss_i_minus_1 = combined_df['mse'].shift(1)
    comp_i = combined_df['complexity']
    comp_i_minus_1 = combined_df['complexity'].shift(1)
    combined_df['scores'] = -(np.log(loss_i) - np.log(loss_i_minus_1)) / (comp_i - comp_i_minus_1)
    combined_df['scores'] = combined_df['scores'].fillna(0.0)   
    combined_df['scores'] = combined_df['scores'].replace([np.inf, -np.inf], 0.0)
    return combined_df

def get_complexity_accuracy(X, y_true, equations_df, variables, llm_suggestions=None):
    # Assume that the X df is defines columns in the same order as is in FeynmanEquations.csv. 
    # 1000 rows for speed
    mse_pysr = list(equations_df['lambda_format'].apply(lambda eq : get_accuracy(eq,X,y_true)) )
    complexity_pysr = list(equations_df['complexity'])
    mse_complexity_llm = []
    if llm_suggestions:        
        for llm_eq in llm_suggestions:
            try:
                mse_complexity_llm.append(get_string_accuracy(llm_eq,X,y_true,variables))      
            except Exception:
                pass
                
    return list(zip(mse_pysr,complexity_pysr)),mse_complexity_llm


import matplotlib.pyplot as plt
import numpy as np
import os

def plot_complexity_accuracy(name, data, guided):
    prefix = "guided" if guided else "unguided"
    save_dir = f'complexity_accuracy_plots_bonus_all_{prefix}/{name}'    
    os.makedirs(save_dir, exist_ok=True)
    
    plt.figure(figsize=(10, 6))
    cmap = plt.get_cmap('nipy_spectral')
    colors = [cmap(i) for i in np.linspace(0, 0.95, 30)] 
    
    for idx, (key, val) in enumerate(data.items()):
        # Unpack the new data structure
        arr, pysr_rate, llm_rate = val
        pysr_data, llm_data = arr
        
        color = colors[idx % len(colors)] 
        
        pysr_mse = [mse for mse, comp in pysr_data]
        pysr_comp = [comp for mse, comp in pysr_data]
        
        # Format the label to include the PySR fake variable percentage
        pysr_label = f'{key} PySR [{pysr_rate:.0%} fake]'
        plt.scatter(pysr_comp, pysr_mse, color=color, alpha=0.3, label=pysr_label)
        
        # If LLM data exists, plot it with its specific fake rate
        if llm_data and llm_rate is not None:
            llm_mse = [mse for mse, comp in llm_data]
            llm_comp = [comp for mse, comp in llm_data]
            llm_label = f'{key} LLM [{llm_rate:.0%} fake]'
            
            plt.scatter(llm_comp, llm_mse, color=color, marker='x', s=100, linewidths=2, label=llm_label)
            
    plt.title(f'Complexity vs. MSE Evolution ({name})')
    plt.xlabel('Complexity (Number of Nodes)')
    plt.ylabel('Mean Squared Error (MSE)')
    plt.yscale('log')
    
    # Adjust legend so it fits well with the longer labels
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize='small')
    plt.grid(True, which="both", ls="--", alpha=0.5)
    
    save_path = os.path.join(save_dir, 'complexity-accuracy-plots.png')
    plt.savefig(save_path, bbox_inches='tight')
    plt.close()

In [ ]:
import openai
from typing import List,Tuple,Any
import json
import pandas as pd
import re

def call_model(schema:dict[str,Any],
              equations:pd.DataFrame,
              meta:pd.DataFrame,
              df_name:str,
              safe_vars:List[str],
              current_units:dict,
              target_variable:str,
              target_unit:str,
              MAX_ATTEMPTS:int=20,
              MAX_REQ_EXPRS:int=3,
              error_info=None,
              score_improvement_info=None) -> List[Any]:   

    client = openai.OpenAI(
        base_url="https://eleanora-unaggravating-ochlocratically.ngrok-free.dev/v1", 
        api_key = "sk-no-key-required"
    )
    parsed=None
    out='{}'
    
    allowed_vars_regex = "|".join(re.escape(v) for v in safe_vars)
    regex_string = rf"^([0-9+*/^() .-]|{allowed_vars_regex}|sin|cos|exp|log|sqrt)+$"
    schema["properties"]["expressions"]["items"]["pattern"] = regex_string
    correct_expr_list=[]
    wrong_expr_list=[]
    attempts=0
    var_descriptions = "\n".join([f"- {var}: {desc}" for var, desc in current_units.items()])
    
    while len(correct_expr_list) < MAX_REQ_EXPRS: # either get 3 correct equations or no
        if attempts == MAX_ATTEMPTS:
            break  

        completion = client.chat.completions.create(
            model="local-model",
            messages=[
                {
                    "role": "system",
                    "content": f"""You are an expert physicist and an AI assistant designed to guide a symbolic regression algorithm 
                    by acting as an intelligent crossover operator.  
                                CRITICAL CONSTRAINTS:
                                1. Output MUST be a valid JSON object strictly following this schema: {json.dumps(schema)}
                                """
                },
                # idea is to take two random equations from pareto front, pass it to model
                # then re prompt until it can generate something whose MSE is lower than the worst equation currently being evolved by pysr. 
                
                {
                    "role": "user",
                    "content": f'''
                                {error_info if error_info is not None else ""}
                                
                                Your task is to generate THREE candidate mathematical expressions for the target physical quantity,
                                by recombining and mutating any of the equations given that these are the top five expressions 
                                currently being evolved by the symbolic regression algorithm: 
                                
                                {score_improvement_info if score_improvement_info is not None else ""}
                                
                                {equations.sort_values(by='score')['sympy_format'].iloc[:5].values}
                                
                                METADATA: 
                                TARGET QUANTITY: {target_variable}
                                TARGET UNIT AND DESCRIPTION: {target_unit}
                                AVAILABLE VARIABLES & PHYSICS CONTEXT:
                                {var_descriptions}
                                
                                STRICT REQUIREMENTS:
                                1. Expressions MUST be valid Julia syntax (i.e. convert ** to ^ in your final response)
                                2. You must ONLY use the most physically relevant variables from the list.
                                3. Use the EXACT variable names provided.
                                '''
                } 
            ],
            response_format={
                "type": "json_object",
                "schema": schema
            },
            temperature=0.3, 
        )

# give it two equations from pareto front and evaulate the score and make it give three new equations.
# evaluate new baseline: 1+1 EA. ... 
# TODO: Try to not  add the hall of fame        
#TODO: in the final report, say something about whether or not the output was used, 
# TODO: how often it was syntactically correct, whether or not it copid the call of fame.
# take population, take two individuals from population (two ways: first way: piuck 2 indiviudals and ask LLM to pick one. as opposed to randomly picking two individuals) 
# use other bselines... (risk is there that it does not work. ) 
# Check if it works on a harder dataset. 
# take equations, MSE, send it back to it and reprompt until mse threshold is reached. 

        try:
            out=completion.choices[0].message.content
            
            print(f"validating {out} ... ")
            parsed = ResponseStructure.model_validate_json(out)
            print("validated successfully")           
            
            for eq in parsed.expressions:
                if eq not in correct_expr_list:
                    correct_expr_list.append(eq)              
        except Exception as e:
            wrong_expr_list.append(out)       
            print(f"Validation failed with {e}. Retrying. Attempt# {attempts+1}")
            
        attempts+=1
    
    print("final expression list: ")
    print(correct_expr_list)
    return correct_expr_list

In [ ]:
UNARY_OPERATORS=["sqrt","exp","sin","cos","log"]
BINARY_OPERATORS=["+", "*", "/", "^","-"]


def get_variables(list_str): # returns variables in a list of strings
    return set([node.id for formula in list_str for node in ast.walk(ast.parse(formula.replace('^', '**'), mode='eval'))
                                if isinstance(node, ast.Name) and node.id not in set(UNARY_OPERATORS)
                                ])

def run_search(df_dict,fresh_start=False,guided=False,toggle_distractors=False):
    MAX_CALLS=29
    MAX_REPROMPTS=10

    c=0
    best_list=[]
    if fresh_start is False:
        # read the file where we have stopped. 
        if os.path.exists('current_run_bonus.txt'):
            with open ('current_run_bonus.txt','r') as f:
                already_read=set(f.read().splitlines())
            all_dfs = set(df_dict.keys())
            to_read=all_dfs-already_read
            # re-create df_dict so next code can be reused
            df_dict={fname:df_dict[fname] for fname in to_read}  
         
        else:                        
            print("current_run.txt does not exist. Reverting to fresh start.")
    else:
        if os.path.exists('current_run_bonus.txt'):
            # remove it
            os.remove('current_run_bonus.txt')
        if guided and os.path.exists('best_eqs_all_bonus_guided.csv'):
                os.remove('best_eqs_all_bonus_guided.csv')
           
        elif not guided and os.path.exists('best_eqs_all_bonus_unguided.csv'):
                os.remove('best_eqs_all_bonus_unguided.csv')

    for name,df in df_dict.items():
        if c==20:
            break
        num_vars = int(df_meta.loc[df_meta['Filename'] == name, '# variables'].values[0])
        raw_vars = [df_meta.loc[df_meta['Filename'] == name, f'v{i+1}_name'].values[0] for i in range(num_vars)]
        variables = [f"{v}_var" for v in raw_vars]
        target_variable = df_meta.loc[df_meta['Filename']==name, 'Output'].values[0]
        print("Target variable: ",target_variable)
        current_units = {raw: unit_map.get(raw, {}).get('dimensionality') for raw in raw_vars}
        target_unit = unit_map.get(target_variable, {}).get('dimensionality')
        print("Target unit: ",target_unit)
        llm_units_context = {
            f"{raw}_var": f"{unit_map.get(raw, {}).get('dimensionality')} ({unit_map.get(raw, {}).get('Units')})"
            for raw in raw_vars
        }
        llm_target_context = f"{target_unit} ({unit_map.get(target_variable, {}).get('Units')})"
        y = df.iloc[:10000, -1].values 
        X = df.iloc[:10000, -(num_vars + 1):-1].copy()
        # hoping and praying that order is kept the same in the metadata file and in the dataset
        X.columns = variables
        distractor_set=set()
        if toggle_distractors:
        # Adding dummy variables for stress testing ....
            all_distractors = {'temperature_var':'T', 'Energy_var':'U', 'luminosity_var':'cd', 'pressure_var':'Pa', 'entropy_var':'J/K'}
            # TODO: add columns that are a random combination of other columns to throw pysr off. The LLM will hopefully ignore the irrelevant variables. 
            
            three = random.sample(list(all_distractors.items()),3) # list of tuples 
            num = len(X.columns)
            # get num number of random ints in the range 0 - 10, so we can do a weighted sum.     
            for var,unit in three:
                X[var] = sum(X.iloc[:,i].values*val for i,val in enumerate(random.sample(range(10),num)))
                variables.append(var)
                current_units[var]=unit
            num_vars=len(variables)
            distractor_set=set([var for var, _ in three])
            print(f"Bloated X shape to {X.shape}. Variables are now: {variables}")
            
        print(f"Going through DF {c+1} solving for equation {name}, X shape: {X.shape}, y shape: {y.shape}")
        # logger_spec = TensorBoardLoggerSpec(
        #                 log_dir="logs/run",
        #                 log_interval=5,  # Log every 5 iterations
        #                 )   
        #trying to  restrict pysr..
        model=PySRRegressor(niterations=5, 
                            warm_start=True,
                            guesses=[],
                            # populations=5,
                            # population_size=20,
                            # tournament_selection_n=2,
                            batching=True,
                            batch_size=32,
                            verbosity=0,
                            dimensional_constraint_penalty=1e5,
                            # constraints={"sin": 10, "cos": 10,
                            #             "exp": 20, "log": 20, "sqrt": 20,
                            #             "pow": (-1, 20)},
                            # nested_constraints={"sin": {"sin": 0, "cos": 0},
                            #                     "cos": {"sin": 0, "cos": 0},
                            #                     "exp": {"exp":0, "log": 0},
                            #                     "log": {"exp": 0, "log": 0},
                            #                     "sqrt": {"sqrt": 0}},
                            unary_operators=UNARY_OPERATORS,
                            binary_operators=BINARY_OPERATORS,
                            fraction_replaced_guesses=0.001, # default is 0.001
                            # logger_spec=logger_spec# constraints taken from paper. 
                            )
        model.fit(X,y,X_units=list(current_units.values()),y_units=target_unit)
        data={}
        pysr_vars = get_variables(model.equations_['sympy_format'].astype(str).tolist())
        pysr_fake_rate = len(distractor_set.intersection(pysr_vars)) / len(pysr_vars) if pysr_vars else 0.0
        arr = get_complexity_accuracy(X, y, model.equations_, variables)
        data['Initial Baseline'] = (arr, pysr_fake_rate, None)
        for iter in range (MAX_CALLS):

            if guided and random.random()<0.1: # 10% of the time
                print(f"LLM called. Sending equations and meta info") 
                print(model.equations_['sympy_format'])               
                llm_guesses = call_model(schema, model.equations_, df_meta, name, variables, llm_units_context, target_variable, target_unit)
                
                attempts = 0
                success = False
                
                while attempts<MAX_REPROMPTS:                    
                    try:
                        # score defined as $$\text{score} = - \frac{\log(\text{loss}_i) - \log(\text{loss}_{i-1})}{\text{complexity}_i - \text{complexity}_{i-1}}$$
                        all_scores=get_scores(X,y,model.equations_,variables,llm_guesses)
                        # lowest PySR score
                        lowest_pysr_score=all_scores[all_scores['source']=='PySR']['scores'].min()
                        best_llm_eqs =  all_scores[(all_scores['source']=='LLM') & (all_scores['scores'] > lowest_pysr_score)]
                        if not best_llm_eqs.empty:
                            
                            best_llm_eqs = best_llm_eqs['sympy_format'].tolist()                            
                            model.set_params(guesses=best_llm_eqs)
                            model.fit(X, y,X_units=list(current_units.values()), y_units=target_unit) 
                            model.set_params(guesses=[])
                            # logging stuff for 
                            pysr_vars = get_variables(model.equations_['sympy_format'].astype(str).tolist())
                            llm_response_vars = get_variables(best_llm_eqs)
                            
                            
                            pysr_fake_rate = len(distractor_set.intersection(pysr_vars)) / len(pysr_vars) if pysr_vars else 0.0
                            llm_fake_rate = len(distractor_set.intersection(llm_response_vars)) / len(llm_response_vars) if llm_response_vars else 0.0
                            
                            arr = get_complexity_accuracy(X, y, model.equations_, variables, best_llm_eqs) 
                            data[f'Iter {iter+1}'] = (arr, pysr_fake_rate, llm_fake_rate)
                            
                            success = True
                            break

                        else:
                            print(f"Valid syntax, but scores too low. Reprompting (Attempt {attempts+1})")
                            llm_string = f'''
                            Your previously generated guesses have a complexity-accuracy trade-off score as follows (higher is better):
                            {all_scores[all_scores['source']=='LLM'][['sympy_format','scores']]}
                            The best performing equations currently can be found below. Please execute intelligent crossover again 
                            and improve on the score.
                            '''
                            llm_guesses = call_model(schema, model.equations_, df_meta, name, variables, llm_units_context, target_variable,llm_target_context, score_improvement_info=llm_string)                               
                        
                    except Exception as e:
                        e_str = str(e)
                        print(f"Exception encountered: {e_str}. Reprompting for syntax fix (Attempt {attempts+1})") 
                        message = e_str.split('Stacktrace:', 1)[0] if 'Stacktrace' in e_str else e_str
                        message += f'\n\nThe error was caused by these guesses: {llm_guesses}. Please re-generate valid guesses.'
                        
                        llm_guesses = call_model(schema, model.equations_, df_meta, name, variables, llm_units_context, target_variable,llm_target_context, error_info=message)
                    attempts += 1

                if not success:
                    print("LLM failed to produce valid/high-scoring equations. Falling back to unguided PySR.")
                    
                    model.set_params(guesses=[])
                    model.fit(X, y,X_units=list(current_units.values()),y_units=target_unit)                    
                    # Standard logging for an unguided step
                    pysr_vars = get_variables(model.equations_['sympy_format'].astype(str).tolist())
                    pysr_fake_rate = len(distractor_set.intersection(pysr_vars)) / len(pysr_vars) if pysr_vars else 0.0
                    arr = get_complexity_accuracy(X, y, model.equations_, variables)
                    data[f'Iter {iter+1}'] = (arr, pysr_fake_rate, None)
            else:
                # continue as normal 
                model.fit(X,y,X_units=list(current_units.values()),y_units=target_unit)
                pysr_vars = get_variables(model.equations_['sympy_format'].astype(str).tolist())
                pysr_fake_rate = len(distractor_set.intersection(pysr_vars)) / len(pysr_vars) if pysr_vars else 0.0
                arr = get_complexity_accuracy(X, y, model.equations_, variables)
                data[f'Iter {iter+1}'] = (arr, pysr_fake_rate, None)
        # plot this
        if data: 
            plot_complexity_accuracy(name, data, guided)
        

        best=model.equations_.sort_values("score",axis=0,ascending=False).iloc[[0]].copy() # score chooses the equation with the best complexity-accuracy trade off.
        best["Filename"] = name 
        
        if guided:
            best.to_csv('best_eqs_all_bonus_guided.csv', mode='a', index=False, header=not os.path.exists('best_eqs_all_bonus_guided.csv'))
        else:
            best.to_csv('best_eqs_all_bonus_unguided.csv', mode='a', index=False, header=not os.path.exists('best_eqs_all_bonus_unguided.csv'))

            
        best_list.append(best)
        # save the name of the df into a text file 
        with open ('current_run_bonus.txt','a') as f:
            f.write(f'{name}\n')
        c+=1

In [14]:
run_search(df_dict,fresh_start=True,guided=False)

Target variable:  K
Target unit:  m^2 * s^-2 * kg
Going through DF 1 solving for equation test_8, X shape: (10000, 4), y shape: (10000,)
Target variable:  F
Target unit:  m * s^-2 * kg
Going through DF 2 solving for equation test_12, X shape: (10000, 4), y shape: (10000,)
Target variable:  r
Target unit:  m
Going through DF 3 solving for equation test_3, X shape: (10000, 4), y shape: (10000,)
Target variable:  v
Target unit:  m * s^-1
Going through DF 4 solving for equation test_4, X shape: (10000, 5), y shape: (10000,)
Target variable:  Volt
Target unit:  V
Going through DF 5 solving for equation test_13, X shape: (10000, 4), y shape: (10000,)
Target variable:  E_n
Target unit:  m^2 * s^-2 * kg
Going through DF 6 solving for equation test_17, X shape: (10000, 6), y shape: (10000,)
Target variable:  A
Target unit:  m^2
Going through DF 7 solving for equation test_20, X shape: (10000, 7), y shape: (10000,)
Target variable:  pr
Target unit:  m^-1 * s^-2 * kg
Going through DF 8 solving for equation test_19, X shape: (10000, 5), y shape: (10000,)
Target variable:  Pwr
Target unit:  m^2 * s^-3 * kg
Going through DF 9 solving for equation test_9, X shape: (10000, 5), y shape: (10000,)
Target variable:  rho_0
Target unit:  m^-3 * kg
Going through DF 10 solving for equation test_18, X shape: (10000, 4), y shape: (10000,)
Target variable:  k
Target unit:  m^-1
Going through DF 11 solving for equation test_2, X shape: (10000, 6), y shape: (10000,)
Target variable:  omega_0
Target unit:  s^-1
Going through DF 12 solving for equation test_15, X shape: (10000, 4), y shape: (10000,)
Target variable:  alpha
Target unit:
Going through DF 13 solving for equation test_6, X shape: (10000, 7), y shape: (10000,)
Target variable:  t
Target unit:  s
Going through DF 14 solving for equation test_5, X shape: (10000, 4), y shape: (10000,)
Target variable:  E_n
Target unit:  m^2 * s^-2 * kg
Going through DF 15 solving for equation test_16, X shape: (10000, 6), y shape: (10000,)
Target variable:  A
Target unit:  m^2
Going through DF 16 solving for equation test_1, X shape: (10000, 7), y shape: (10000,)
Target variable:  I
Target unit:  m^2 * s^-3 * kg * V^-1
Going through DF 17 solving for equation test_11, X shape: (10000, 4), y shape: (10000,)
Target variable:  H_G
Target unit:  s^-1
Going through DF 18 solving for equation test_7, X shape: (10000, 5), y shape: (10000,)
Target variable:  theta1
Target unit:
Going through DF 19 solving for equation test_10, X shape: (10000, 3), y shape: (10000,)
Target variable:  Volt
Target unit:  V
Going through DF 20 solving for equation test_14, X shape: (10000, 5), y shape: (10000,)

In [ ]:
run_search(df_dict,fresh_start=False,guided=True)

Target variable:  k
Target unit:  Wave number
Bloated X shape to (10000, 6). Variables are now: ['alpha_var', 'n_var', 'd_var', 'entropy_var', 'luminosity_var', 'temperature_var']
Going through DF 1 solving for equation III.15.27, X shape: (10000, 6), y shape: (10000,)
LLM called. Sending equations and meta info
validating { "expressions": [ "alpha_var * 6.283857 / (d_var * n_var) - (-1) * 0.2810383 * cos(alpha_var) / (luminosity_var * (alpha_var * 6.283857 / (d_var * n_var)))", "6.283857 * alpha_var / (d_var * n_var) - 0.009192648 / entropy_var", "exp(28.335733 / temperature_var) + alpha_var * 6.283857 / (d_var * n_var)" ] } ...
validated successfully
final expression list:
['alpha_var * 6.283857 / (d_var * n_var) - (0 - 1) * 0.2810383 * cos(alpha_var) / (luminosity_var * (alpha_var * 6.283857 / (d_var * n_var)))', '6.283857 * alpha_var / (d_var * n_var) - 0.009192648 / entropy_var', 'exp(28.335733 / temperature_var) + alpha_var * 6.283857 / (d_var * n_var)']
[np.float64(0.00162797481150149), np.float64(0.0016285620942658862), np.float64(12.956945222388999)]
[22, 15, 16]
Valid syntax, but scores too low. Reprompting (Attempt 1)
validating {"expressions": ["6.283857 * alpha_var / (d_var * n_var) - 0.009192648 / entropy_var + exp(28.335733 / temperature_var)", "alpha_var * 6.283857 / (d_var * n_var) - (-1) * 0.2810383 * cos(alpha_var) / (luminosity_var * (alpha_var * 6.283857 / (d_var * n_var)))", "exp(28.335733 / temperature_var) + alpha_var * 6.283857 / (d_var * n_var) - (-1) * 0.2810383 * cos(alpha_var) / (alpha_var * luminosity_var)"]} ...
validated successfully
final expression list:
['6.283857 * alpha_var / (d_var * n_var) - 0.009192648 / entropy_var + exp(28.335733 / temperature_var)', 'alpha_var * 6.283857 / (d_var * n_var) - (0 - 1) * 0.2810383 * cos(alpha_var) / (luminosity_var * (alpha_var * 6.283857 / (d_var * n_var)))', 'exp(28.335733 / temperature_var) + alpha_var * 6.283857 / (d_var * n_var) - (0 - 1) * 0.2810383 * cos(alpha_var) / (alpha_var * luminosity_var)']
[np.float64(12.955531723560389), np.float64(0.00162797481150149), np.float64(12.953682746242702)]
[21, 22, 26]
Valid syntax, but scores too low. Reprompting (Attempt 2)
validating {"expressions": ["alpha_var * 6.283857 / (d_var * n_var) - (-1) * 0.2810383 * cos(alpha_var) / (luminosity_var * alpha_var)", "6.283857 * alpha_var / (d_var * n_var) + exp(-entropy_var / temperature_var)", "alpha_var * 6.283857 / (d_var * n_var) - 0.009192648 / entropy_var + log(luminosity_var)"]} ...
validated successfully
final expression list:
['alpha_var * 6.283857 / (d_var * n_var) - (0 - 1) * 0.2810383 * cos(alpha_var) / (luminosity_var * alpha_var)', '6.283857 * alpha_var / (d_var * n_var) + exp((0 - entropy_var) / temperature_var)', 'alpha_var * 6.283857 / (d_var * n_var) - 0.009192648 / entropy_var + log(luminosity_var)']
[np.float64(0.0016280005595390808), np.float64(0.025537240115002906), np.float64(18.09839949460611)]
[20, 17, 17]
LLM called. Sending equations and meta info
validating {"expressions": ["alpha_var * 6.284336 / (d_var * n_var) - 0.009192648 / entropy_var", "alpha_var * 6.284336 / (d_var * n_var) - (0.001721711 - 0.20370589 * 1.3804214) * cos(alpha_var) / (alpha_var * luminosity_var)", "alpha_var * 6.284336 / (d_var * n_var) - (0.001721711 - 1 * 0.20370589) * cos(alpha_var) / (alpha_var * luminosity_var)"]} ...
validated successfully
final expression list:
['alpha_var * 6.284336 / (d_var * n_var) - 0.009192648 / entropy_var', 'alpha_var * 6.284336 / (d_var * n_var) - (0.001721711 - 0.20370589 * 1.3804214) * cos(alpha_var) / (alpha_var * luminosity_var)', 'alpha_var * 6.284336 / (d_var * n_var) - (0.001721711 - 1 * 0.20370589) * cos(alpha_var) / (alpha_var * luminosity_var)']
[np.float64(0.001628677222770898), np.float64(0.001627904997198202), np.float64(0.0016279430237665792)]
[15, 20, 20]
Valid syntax, but scores too low. Reprompting (Attempt 1)
validating {"expressions": ["alpha_var * 6.284336 / (d_var * n_var) - 0.009192648 / entropy_var", "alpha_var * 6.284336 / (d_var * n_var) - (0.001721711 - 0.20370589 * cos(alpha_var)) / (alpha_var * luminosity_var)", "alpha_var * 6.284336 / (d_var * n_var) - (0.001721711 - 0.20370589 * temperature_var) / (alpha_var * luminosity_var)"]} ...
validated successfully
final expression list:
['alpha_var * 6.284336 / (d_var * n_var) - 0.009192648 / entropy_var', 'alpha_var * 6.284336 / (d_var * n_var) - (0.001721711 - 0.20370589 * cos(alpha_var)) / (alpha_var * luminosity_var)', 'alpha_var * 6.284336 / (d_var * n_var) - (0.001721711 - 0.20370589 * temperature_var) / (alpha_var * luminosity_var)']
[np.float64(0.001628677222770898), np.float64(0.0016279354789188612), np.float64(0.003052785277115781)]
[15, 24, 23]
Target variable:  E_n
Target unit:  Energy
Bloated X shape to (10000, 7). Variables are now: ['h_var', 'omega_var', 'kb_var', 'T_var', 'temperature_var', 'magnetic_flux_var', 'pressure_var']
Going through DF 2 solving for equation III.4.33, X shape: (10000, 7), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["8.29452300000000 * kb_var * (T_var - 0.00025586662) + 0.873058408904424 * (-kb_var + log(h_var) / log(pressure_var) + 0.6281389)", "T_var + kb_var - 0.7008144 * sqrt(pressure_var) * T_var * kb_var", "(0.873058408904424 - 0.951032550080713 * T_var) * (-kb_var + log(h_var) / log(pressure_var) + 0.6281389)"]} ...
validated successfully
final expression list:
['8.294523 * kb_var * (T_var - 0.00025586662) + 0.873058408904424 * (0 - kb_var + log(h_var) / log(pressure_var) + 0.6281389)', 'T_var + kb_var - 0.7008144 * sqrt(pressure_var) * T_var * kb_var', '(0.873058408904424 - 0.951032550080713 * T_var) * (0 - kb_var + log(h_var) / log(pressure_var) + 0.6281389)']
[np.float64(5458.754584459644), np.float64(4353.594874487179), np.float64(19.242678844614925)]
[19, 10, 18]
LLM called. Sending equations and meta info
validating { "expressions": [ "-1.2049735^(omega_var - 2.4484591) + T_var*kb_var*sqrt(0.9147975^pressure_var) + T_var*kb_var - 0.03663018", "0.9550858^pressure_var*T_var*kb_var - 1.1897014^(omega_var - 2.450054) + T_var*kb_var", "-1.2049735^(omega_var - 2.4484591) + kb_var*(0.956450469182801^pressure_var*T_var + T_var)" ] } ...
validated successfully
final expression list:
['0 - 1.2049735 ^ (omega_var - 2.4484591) + T_var * kb_var * sqrt(0.9147975 ^ pressure_var) + T_var * kb_var - 0.03663018', '0.9550858 ^ pressure_var * T_var * kb_var - 1.1897014 ^ (omega_var - 2.450054) + T_var * kb_var', '0 - 1.2049735 ^ (omega_var - 2.4484591) + kb_var * (0.956450469182801 ^ pressure_var * T_var + T_var)']
[np.float64(0.035840730965848666), np.float64(0.03609557079652155), np.float64(0.037372043057922896)]
[20, 17, 17]
LLM called. Sending equations and meta info
validating { "expressions": [ "T_var * kb_var", "omega_var^(-0.3823377) + T_var * kb_var", "sqrt(pressure_var) + T_var * kb_var" ] } ...
validated successfully
final expression list:
['T_var * kb_var', 'omega_var ^ (0 - 0.3823377) + T_var * kb_var', 'sqrt(pressure_var) + T_var * kb_var']
[np.float64(0.6115682621261267), np.float64(1.9796040300710462), np.float64(74.5085497782916)]
[3, 7, 7]
Valid syntax, but scores too low. Reprompting (Attempt 1)
validating { "expressions": [ "T_var * kb_var + sqrt(pressure_var)", "omega_var ^ (0 - 0.3823377) + T_var * kb_var", "-1.1081928^h_var + T_var*kb_var + omega_var^(-0.3823377)" ] } ...
validated successfully
final expression list:
['T_var * kb_var + sqrt(pressure_var)', 'omega_var ^ (0 - 0.3823377) + T_var * kb_var', '0 - 1.1081928 ^ h_var + T_var * kb_var + omega_var ^ (0 - 0.3823377)']
[np.float64(74.5085497782916), np.float64(1.9796040300710462), np.float64(0.046958941279541366)]
[7, 7, 12]
Valid syntax, but scores too low. Reprompting (Attempt 2)
validating {"expressions": ["T_var * kb_var + omega_var ^ (-0.3823377)", "1.0527073^(0.92474484 - 1.2867477^(omega_var*(sqrt(pressure_var) + h_var - 1.1781671))) + T_var * kb_var", "T_var * kb_var - (temperature_var * 0.020749142 - 0.6470789)"]} ...
validated successfully
final expression list:
['T_var * kb_var + omega_var ^ (0 - 0.3823377)', '1.0527073 ^ (0.92474484 - 1.2867477 ^ (omega_var * (sqrt(pressure_var) + h_var - 1.1781671))) + T_var * kb_var', 'T_var * kb_var - (temperature_var * 0.020749142 - 0.6470789)']
[np.float64(1.9796040300710462), np.float64(0.6679548816435278), np.float64(0.06313896466420409)]
[7, 20, 8]
LLM called. Sending equations and meta info
validating { "expressions": [ "-1.2178892^((-1.0693725^(h_var - omega_var^h_var) + h_var + omega_var - 6.5455303 + 0.021854274)/0.9626487) + T_var*kb_var + 0.21673767", "T_var*kb_var - (1.1108397^((-1.0693725^(h_var - h_var^omega_var) + h_var + omega_var - 6.5455303 - 0.7694412*(-0.028405048))/0.9626487))^1.8752497 + 0.21673767", "-1.2287941^(h_var + omega_var - 6.6055 - 1*(-0.6232164)) + T_var*kb_var + 0.3836983" ] } ...
validated successfully
final expression list:
['0 - 1.2178892 ^ ((0 - 1.0693725 ^ (h_var - omega_var ^ h_var) + h_var + omega_var - 6.5455303 + 0.021854274) / 0.9626487) + T_var * kb_var + 0.21673767', 'T_var * kb_var - (1.1108397 ^ ((0 - 1.0693725 ^ (h_var - h_var ^ omega_var) + h_var + omega_var - 6.5455303 - 0.7694412 * (0 - 0.028405048)) / 0.9626487)) ^ 1.8752497 + 0.21673767', '0 - 1.2287941 ^ (h_var + omega_var - 6.6055 - 1 * (0 - 0.6232164)) + T_var * kb_var + 0.3836983']
[np.float64(0.012231628376198523), np.float64(0.012138440098834205), np.float64(0.014021368010380847)]
[28, 30, 13]
Valid syntax, but scores too low. Reprompting (Attempt 1)
validating {"expressions": ["-1.2178892**((-1.0693725**(h_var - omega_var) + h_var + omega_var - 6.5455303 + 0.021854274)/0.9626487) + T_var*kb_var + 0.21673767", "T_var*kb_var - (1.1108397**((-1.0693725**(h_var - h_var**omega_var) + h_var + omega_var - 6.5455303 - 0.7694412*(-0.028405048))/0.9626487))**1.8752497 + 0.21673767", "-1.2287941**(h_var + omega_var - 6.6055 - 1*(-0.6232164)) + T_var*kb_var + 0.3836983"]} ...
validated successfully
final expression list:
['0 - 1.2178892 ^ ((0 - 1.0693725 ^ (h_var - omega_var) + h_var + omega_var - 6.5455303 + 0.021854274) / 0.9626487) + T_var * kb_var + 0.21673767', 'T_var * kb_var - (1.1108397 ^ ((0 - 1.0693725 ^ (h_var - h_var ^ omega_var) + h_var + omega_var - 6.5455303 - 0.7694412 * (0 - 0.028405048)) / 0.9626487)) ^ 1.8752497 + 0.21673767', '0 - 1.2287941 ^ (h_var + omega_var - 6.6055 - 1 * (0 - 0.6232164)) + T_var * kb_var + 0.3836983']
[np.float64(0.039909905039616084), np.float64(0.012138440098834205), np.float64(0.014021368010380847)]
[26, 30, 13]
Valid syntax, but scores too low. Reprompting (Attempt 2)
validating {"expressions": ["-1.2178892**((-1.0693725**(h_var - omega_var) + h_var + omega_var - 6.5455303 + 0.021854274)/0.9626487) + T_var*kb_var + 0.21673767", "T_var*kb_var - (1.1108397**((-1.0693725**(h_var - h_var**omega_var) + h_var + omega_var - 6.5455303 - 0.7694412*(-0.028405048))/0.9626487))**1.8752497 + 0.21673767", "-1.2287941**(h_var + omega_var - 6.6055 - 1*(-0.6232164)) + T_var*kb_var + 0.3836983"]} ...
validated successfully
final expression list:
['0 - 1.2178892 ^ ((0 - 1.0693725 ^ (h_var - omega_var) + h_var + omega_var - 6.5455303 + 0.021854274) / 0.9626487) + T_var * kb_var + 0.21673767', 'T_var * kb_var - (1.1108397 ^ ((0 - 1.0693725 ^ (h_var - h_var ^ omega_var) + h_var + omega_var - 6.5455303 - 0.7694412 * (0 - 0.028405048)) / 0.9626487)) ^ 1.8752497 + 0.21673767', '0 - 1.2287941 ^ (h_var + omega_var - 6.6055 - 1 * (0 - 0.6232164)) + T_var * kb_var + 0.3836983']
[np.float64(0.039909905039616084), np.float64(0.012138440098834205), np.float64(0.014021368010380847)]
[26, 30, 13]
Valid syntax, but scores too low. Reprompting (Attempt 3)
validating {"expressions": ["-1.2178892^((-1.0693725^(h_var - omega_var) + h_var + omega_var - 6.5455303 + 0.021854274)/0.9626487) + T_var*kb_var + 0.21673767", "-1.2414361^(-1.1005832^(-omega_var*h_var + cos(T_var)) + h_var + omega_var - 6.555867) + T_var*kb_var + 0.23194571", "T_var*kb_var - (1.1108397^((-1.0693725^(h_var - h_var*omega_var) + h_var + omega_var - 6.5455303 - 0.7694412*(-0.028405048))/0.9626487))**1.8752497 + 0.21673767"]} ...
validated successfully
final expression list:
['0 - 1.2178892 ^ ((0 - 1.0693725 ^ (h_var - omega_var) + h_var + omega_var - 6.5455303 + 0.021854274) / 0.9626487) + T_var * kb_var + 0.21673767', '0 - 1.2414361 ^ (0 - 1.1005832 ^ ((0 - omega_var) * h_var + cos(T_var)) + h_var + omega_var - 6.555867) + T_var * kb_var + 0.23194571', 'T_var * kb_var - (1.1108397 ^ ((0 - 1.0693725 ^ (h_var - h_var * omega_var) + h_var + omega_var - 6.5455303 - 0.7694412 * (0 - 0.028405048)) / 0.9626487)) ^ 1.8752497 + 0.21673767']
[np.float64(0.039909905039616084), np.float64(0.015589203440498817), np.float64(0.019799568547057788)]
[26, 24, 29]
Valid syntax, but scores too low. Reprompting (Attempt 4)
validating {"expressions": ["T_var * kb_var - (1.1108397 ^ ((h_var - omega_var) / 0.9626487)) + 0.21673767", "-1.2178892^(-((h_var - omega_var) / 0.9626487) + cos(T_var)) + T_var*kb_var + 0.23194571", "T_var * kb_var - (1.1108397 ^ ((h_var - omega_var^2) / 0.9626487))^1.8752497 + 0.21673767"]} ...
validated successfully
final expression list:
['T_var * kb_var - 1.1108397 ^ ((h_var - omega_var) / 0.9626487) + 0.21673767', '0 - 1.2178892 ^ (0 - (h_var - omega_var) / 0.9626487 + cos(T_var)) + T_var * kb_var + 0.23194571', 'T_var * kb_var - (1.1108397 ^ ((h_var - omega_var ^ 2) / 0.9626487)) ^ 1.8752497 + 0.21673767']
[np.float64(0.19660569995193786), np.float64(0.2803891189082889), np.float64(0.7604708274662176)]
[16, 18, 20]
Valid syntax, but scores too low. Reprompting (Attempt 5)
validating {"expressions": ["T_var * kb_var - (1.1108397 ^ ((h_var - omega_var) / 0.9626487)) + 0.21673767", "-1.2178892 ** ((h_var - omega_var) / 0.9626487) + T_var * kb_var + 0.23194571", "T_var * kb_var - (1.1108397 ^ ((h_var - omega_var) / 0.9626487)) ** 1.8752497 + 0.21673767"]} ...
validated successfully
final expression list:
['T_var * kb_var - 1.1108397 ^ ((h_var - omega_var) / 0.9626487) + 0.21673767', '0 - 1.2178892 ^ ((h_var - omega_var) / 0.9626487) + T_var * kb_var + 0.23194571', 'T_var * kb_var - (1.1108397 ^ ((h_var - omega_var) / 0.9626487)) ^ 1.8752497 + 0.21673767']
[np.float64(0.19660569995193786), np.float64(0.3072491408308445), np.float64(0.31177827780842937)]
[16, 16, 18]
Valid syntax, but scores too low. Reprompting (Attempt 6)
validating {"expressions": ["T_var * kb_var - 1.1108397 ^ ((h_var - omega_var) / 0.9626487)", "T_var * kb_var - (1.1108397 ^ ((h_var - h_var^omega_var) / 0.9626487))**1.8752497", "-1.2178892**((-1.0693725**(h_var - omega_var**h_var) + h_var + omega_var - 6.5455303 + 0.021854274)/0.9626487) + T_var*kb_var"]} ...
validated successfully
final expression list:
['T_var * kb_var - 1.1108397 ^ ((h_var - omega_var) / 0.9626487)', 'T_var * kb_var - (1.1108397 ^ ((h_var - h_var ^ omega_var) / 0.9626487)) ^ 1.8752497', '0 - 1.2178892 ^ ((0 - 1.0693725 ^ (h_var - omega_var ^ h_var) + h_var + omega_var - 6.5455303 + 0.021854274) / 0.9626487) + T_var * kb_var']
[np.float64(0.29378585718474826), np.float64(0.6368523087213219), np.float64(0.05654682362571319)]
[15, 19, 27]
Valid syntax, but scores too low. Reprompting (Attempt 7)
validating { "expressions": [ "-1.2178892**((-1.0693725**(h_var - omega_var) + h_var + omega_var - 6.5455303 + 0.021854274)/0.9626487) + T_var*kb_var + 0.21673767", "-1.2414361**(-1.1005832**(-omega_var*h_var + cos(T_var)) + h_var + omega_var - 6.555867) + T_var*kb_var + 0.23194571", "T_var*kb_var - (1.1108397**((-1.0693725**(h_var - h_var*omega_var) + h_var + omega_var - 6.5455303 - 0.7694412*(-0.028405048))/0.9626487))**1.8752497 + 0.21673767" ] } ...
validated successfully
final expression list:
['0 - 1.2178892 ^ ((0 - 1.0693725 ^ (h_var - omega_var) + h_var + omega_var - 6.5455303 + 0.021854274) / 0.9626487) + T_var * kb_var + 0.21673767', '0 - 1.2414361 ^ (0 - 1.1005832 ^ ((0 - omega_var) * h_var + cos(T_var)) + h_var + omega_var - 6.555867) + T_var * kb_var + 0.23194571', 'T_var * kb_var - (1.1108397 ^ ((0 - 1.0693725 ^ (h_var - h_var * omega_var) + h_var + omega_var - 6.5455303 - 0.7694412 * (0 - 0.028405048)) / 0.9626487)) ^ 1.8752497 + 0.21673767']
[np.float64(0.039909905039616084), np.float64(0.015589203440498817), np.float64(0.019799568547057788)]
[26, 24, 29]
Valid syntax, but scores too low. Reprompting (Attempt 8)
validating {"expressions": ["T_var * kb_var - (1.1108397 ** ((-1.0693725 ** (h_var - omega_var)) + h_var + omega_var - 6.5455303))", "-1.2178892 ** ((-1.0693725 ** (h_var - omega_var)) + h_var + omega_var - 6.5455303) + T_var * kb_var", "T_var * kb_var - (1.1108397 ** ((-1.0693725 ** (h_var - omega_var)) + h_var + omega_var - 6.5455303)) ** 1.8752497"]} ...
validated successfully
final expression list:
['T_var * kb_var - 1.1108397 ^ (0 - 1.0693725 ^ (h_var - omega_var) + h_var + omega_var - 6.5455303)', '0 - 1.2178892 ^ (0 - 1.0693725 ^ (h_var - omega_var) + h_var + omega_var - 6.5455303) + T_var * kb_var', 'T_var * kb_var - (1.1108397 ^ (0 - 1.0693725 ^ (h_var - omega_var) + h_var + omega_var - 6.5455303)) ^ 1.8752497']
[np.float64(0.0936899551851753), np.float64(0.03587388776215736), np.float64(0.03587390466941112)]
[21, 21, 23]
Valid syntax, but scores too low. Reprompting (Attempt 9)
validating { "expressions": [ "-1.2178892^((-1.0693725^(h_var - omega_var) + h_var + omega_var - 6.5455303 + 0.021854274)/0.9626487) + T_var*kb_var + 0.21673767", "-1.2414361^(-1.1005832^(-omega_var + cos(T_var)) + h_var + omega_var - 6.555867) + T_var*kb_var + 0.23194571", "T_var*kb_var - (1.1108397^((-1.0693725^(h_var - h_var*omega_var) + h_var + omega_var - 6.5455303 - 0.7694412*(-0.028405048))/0.9626487))**1.8752497 + 0.21673767" ] } ...
validated successfully
final expression list:
['0 - 1.2178892 ^ ((0 - 1.0693725 ^ (h_var - omega_var) + h_var + omega_var - 6.5455303 + 0.021854274) / 0.9626487) + T_var * kb_var + 0.21673767', '0 - 1.2414361 ^ (0 - 1.1005832 ^ (0 - omega_var + cos(T_var)) + h_var + omega_var - 6.555867) + T_var * kb_var + 0.23194571', 'T_var * kb_var - (1.1108397 ^ ((0 - 1.0693725 ^ (h_var - h_var * omega_var) + h_var + omega_var - 6.5455303 - 0.7694412 * (0 - 0.028405048)) / 0.9626487)) ^ 1.8752497 + 0.21673767']
[np.float64(0.039909905039616084), np.float64(0.028327976461658078), np.float64(0.019799568547057788)]
[26, 23, 29]
Valid syntax, but scores too low. Reprompting (Attempt 10)
validating {"expressions": ["-1.2178892^((-1.0693725^(h_var - omega_var^h_var) + h_var + omega_var - 6.5455303 + 0.021854274)/0.9626487) + T_var*kb_var + 0.21673767", "-1.2414361^(-1.1005832^(-omega_var^h_var + cos(T_var)) + h_var + omega_var - 6.555867) + T_var*kb_var + 0.23194571", "T_var*kb_var - (1.1108397^((-1.0693725^(h_var - h_var^omega_var) + h_var + omega_var - 6.5455303 - 0.7694412*(-0.028405048))/0.9626487))**1.8752497 + 0.21673767"]} ...
validated successfully
final expression list:
['0 - 1.2178892 ^ ((0 - 1.0693725 ^ (h_var - omega_var ^ h_var) + h_var + omega_var - 6.5455303 + 0.021854274) / 0.9626487) + T_var * kb_var + 0.21673767', '0 - 1.2414361 ^ (0 - 1.1005832 ^ (0 - omega_var ^ h_var + cos(T_var)) + h_var + omega_var - 6.555867) + T_var * kb_var + 0.23194571', 'T_var * kb_var - (1.1108397 ^ ((0 - 1.0693725 ^ (h_var - h_var ^ omega_var) + h_var + omega_var - 6.5455303 - 0.7694412 * (0 - 0.028405048)) / 0.9626487)) ^ 1.8752497 + 0.21673767']
LLM failed to produce valid/high-scoring equations. Falling back to unguided PySR.
LLM called. Sending equations and meta info
validating {"expressions": ["T_var * kb_var - (1.1108397^1.8752497)^((-1.0693725^(h_var - h_var^omega_var) + h_var + omega_var - 6.5455303 - 0.7694412*(-0.028405048))/0.9626487) + 0.21673767", "-1.2414361^(-1.1005832^(-h_var^omega_var - 1.1699271) + h_var + omega_var - 6.555867) + T_var * kb_var + 0.23194571", "-1.2178892^((-1.0693725^(omega_var - omega_var^h_var) + h_var + omega_var - 6.5455303 + 0.021854274)/0.9626487) + T_var * kb_var + 0.21673767"]} ...
validated successfully
final expression list:

┌ Warning: Guess expression '((-0.008859801 - (1.2286419 ^ ((((-0.0029473524 - (1.0714921 ^ ((0.0014616133 - (x2 ^ x1)) + log(x2 * x7)))) + x1) + (0.99747086 * x2)) - 6.5269346))) + (x4 * x3)) + 0.20788364' has complexity 32 > maxsize (30).
└ @ SymbolicRegression.SearchUtilsModule ~/.julia/packages/SymbolicRegression/fLqXe/src/SearchUtils.jl:814

Target variable:  E_n
Target unit:  Energy
Bloated X shape to (10000, 7). Variables are now: ['m_var', 'omega_var', 'omega_0_var', 'x_var', 'entropy_var', 'luminosity_var', 'temperature_var']
Going through DF 3 solving for equation I.24.6, X shape: (10000, 7), y shape: (10000,)
LLM called. Sending equations and meta info
validating { "expressions": [ "sqrt(x_var)*(omega_0_var + temperature_var) - 31.589312", "omega_var^x_var - sqrt(x_var) + 0.12032092*exp(0.999996788604171^x_var + 0.11682249*entropy_var) - 0.12032092*exp(luminosity_var/temperature_var + temperature_var/luminosity_var)", "m_var*exp(x_var)" ] } ...
validated successfully
final expression list:
['sqrt(x_var) * (omega_0_var + temperature_var) - 31.589312', 'omega_var ^ x_var - sqrt(x_var) + 0.12032092 * exp(0.999996788604171 ^ x_var + 0.11682249 * entropy_var) - 0.12032092 * exp(luminosity_var / temperature_var + temperature_var / luminosity_var)', 'm_var * exp(x_var)']
[np.float64(31.539603007512), np.float64(9.693759605984031), np.float64(73.86972097060496)]
[9, 33, 4]
Valid syntax, but scores too low. Reprompting (Attempt 1)
validating {"expressions": ["m_var * exp(x_var)", "omega_var^x_var + sqrt(temperature_var) * omega_0_var", "sqrt(x_var) * (omega_0_var + temperature_var) - m_var"]} ...
validated successfully
final expression list:
['m_var * exp(x_var)', 'omega_var ^ x_var + sqrt(temperature_var) * omega_0_var', 'sqrt(x_var) * (omega_0_var + temperature_var) - m_var']
[np.float64(73.86972097060496), np.float64(106.7031926111523), np.float64(938.8626735910136)]
[4, 9, 11]
Valid syntax, but scores too low. Reprompting (Attempt 2)
validating {"expressions": ["omega_var^x_var + sqrt(temperature_var) * omega_0_var", "m_var * exp(x_var) + sin(entropy_var)", "sqrt(x_var) * (omega_0_var + temperature_var) - log(luminosity_var)"]} ...
validated successfully
final expression list:
['omega_var ^ x_var + sqrt(temperature_var) * omega_0_var', 'm_var * exp(x_var) + sin(entropy_var)', 'sqrt(x_var) * (omega_0_var + temperature_var) - log(luminosity_var)']
[np.float64(106.7031926111523), np.float64(74.17520008160233), np.float64(839.9783797530985)]
[9, 7, 12]
Valid syntax, but scores too low. Reprompting (Attempt 3)
validating {"expressions": ["m_var * exp(x_var) + sin(entropy_var)", "omega_var ^ x_var + sqrt(temperature_var) * omega_0_var", "sqrt(x_var) * (omega_0_var + temperature_var) - 31.589312"]} ...
validated successfully
final expression list:
['m_var * exp(x_var) + sin(entropy_var)', 'omega_var ^ x_var + sqrt(temperature_var) * omega_0_var', 'sqrt(x_var) * (omega_0_var + temperature_var) - 31.589312']
[np.float64(74.17520008160233), np.float64(106.7031926111523), np.float64(31.539603007512)]
[7, 9, 9]
Valid syntax, but scores too low. Reprompting (Attempt 4)
validating {"expressions": ["sqrt(x_var) * (omega_0_var + temperature_var) - 31.589312", "omega_var^x_var + 0.12032092*exp(0.11682249*entropy_var + cos(0.0025343234^x_var)) - sqrt(log(entropy_var))", "m_var * exp(x_var) + sin(omega_0_var * x_var)"]} ...
validated successfully
final expression list:
['sqrt(x_var) * (omega_0_var + temperature_var) - 31.589312', 'omega_var ^ x_var + 0.12032092 * exp(0.11682249 * entropy_var + cos(0.0025343234 ^ x_var)) - sqrt(log(entropy_var))', 'm_var * exp(x_var) + sin(omega_0_var * x_var)']
[np.float64(31.539603007512), np.float64(10.109058119991756), np.float64(74.71704452958349)]
[9, 21, 9]
LLM called. Sending equations and meta info
validating {"expressions": ["18.3165100000000 * x_var * (temperature_var - 25.014395) - 1 * 0.41040546", "sqrt(omega_var) + omega_var^x_var - x_var^log(x_var) + 0.40397146 * exp(0.11493382 * entropy_var) - cos(omega_0_var) - cos(omega_var - 0.049936473) - 5.24304295089097", "-m_var + 0.2857487 * omega_0_var^omega_var + omega_var^x_var + 0.2857487 * exp(0.12209614 * entropy_var) - 2 * sin(omega_var) - 1.08752241356213"]} ...
validated successfully
final expression list:
['18.31651 * x_var * (temperature_var - 25.014395) - 1 * 0.41040546', 'sqrt(omega_var) + omega_var ^ x_var - x_var ^ log(x_var) + 0.40397146 * exp(0.11493382 * entropy_var) - cos(omega_0_var) - cos(omega_var - 0.049936473) - 5.24304295089097', '0 - m_var + 0.2857487 * omega_0_var ^ omega_var + omega_var ^ x_var + 0.2857487 * exp(0.12209614 * entropy_var) - 2 * sin(omega_var) - 1.08752241356213']
[np.float64(164854.05456848931), np.float64(6.133721095337384), np.float64(6.175993652976195)]
[8, 30, 23]
Target variable:  prob
Target unit:  Dimensionless
Bloated X shape to (10000, 9). Variables are now: ['p_d_var', 'Ef_var', 't_var', 'h_var', 'omega_var', 'omega_0_var', 'luminosity_var', 'magnetic_flux_var', 'pressure_var']
Going through DF 4 solving for equation III.9.52, X shape: (10000, 9), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["5.95819384237225*Ef_var*p_d_var/h_var", "Ef_var*p_d_var*(Ef_var/h_var + t_var)", "-2.5771537 + p_d_var*(Ef_var*(h_var + 4.001041) + Ef_var + Ef_var)/h_var"]} ...
validated successfully
final expression list:
['5.95819384237225 * Ef_var * p_d_var / h_var', 'Ef_var * p_d_var * (Ef_var / h_var + t_var)', '0 - 2.5771537 + p_d_var * (Ef_var * (h_var + 4.001041) + Ef_var + Ef_var) / h_var']
[np.float64(142.52489709282074), np.float64(152.9883260847878), np.float64(140.00372228262316)]
[7, 10, 16]
LLM called. Sending equations and meta info
validating { "expressions": [ "14.8005400000000 * p_d_var / h_var", "24.302235 * Ef_var / (h_var * omega_var)", "(p_d_var / h_var) ^ 2 * Ef_var" ] } ...
validated successfully
final expression list:
['14.80054 * p_d_var / h_var', '24.302235 * Ef_var / (h_var * omega_var)', '(p_d_var / h_var) ^ 2 * Ef_var']
[np.float64(161.38368112855872), np.float64(222.07895474625724), np.float64(309.7485067579927)]
[6, 9, 8]
Target variable:  omega
Target unit:  Frequency
Bloated X shape to (10000, 6). Variables are now: ['c_var', 'v_var', 'omega_0_var', 'pressure_var', 'luminosity_var', 'magnetic_flux_var']
Going through DF 5 solving for equation I.34.14, X shape: (10000, 6), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["omega_0_var + 6.804015/c_var", "omega_0_var*exp(v_var/(c_var - (v_var - cos(-0.9358805))/c_var))", "omega_0_var*exp(v_var/(c_var - (-0.7568081^v_var + v_var)/c_var))"]} ...
validated successfully
final expression list:
['omega_0_var + 6.804015 / c_var', 'omega_0_var * exp(v_var / (c_var - (v_var - cos(0 - 0.9358805)) / c_var))', 'omega_0_var * exp(v_var / (c_var - (0 - 0.7568081 ^ v_var + v_var) / c_var))']
[np.float64(0.2890444315639246), np.float64(0.0018667133379457357), np.float64(0.0018213036448885241)]
[7, 17, 21]
LLM called. Sending equations and meta info
validating {"expressions": ["omega_0_var * exp(v_var / (c_var - (-0.6582201^v_var + v_var - 0.13483068) / c_var))", "omega_0_var * exp(v_var / (c_var - (v_var - sqrt(0.5775814^v_var)) / c_var))", "omega_0_var * exp(v_var / (c_var - (-0.7568081^v_var + v_var) / c_var))"]} ...
validated successfully
final expression list:
['omega_0_var * exp(v_var / (c_var - (0 - 0.6582201 ^ v_var + v_var - 0.13483068) / c_var))', 'omega_0_var * exp(v_var / (c_var - (v_var - sqrt(0.5775814 ^ v_var)) / c_var))', 'omega_0_var * exp(v_var / (c_var - (0 - 0.7568081 ^ v_var + v_var) / c_var))']
[np.float64(0.0018211063024084488), np.float64(0.0018211315234790298), np.float64(0.0018213036448885241)]
[22, 23, 21]
Target variable:  omega
Target unit:  Frequency
Bloated X shape to (10000, 6). Variables are now: ['mom_var', 'B_var', 'h_var', 'magnetic_flux_var', 'pressure_var', 'luminosity_var']
Going through DF 6 solving for equation III.7.38, X shape: (10000, 6), y shape: (10000,)
Target variable:  E_n
Target unit:  Energy
Bloated X shape to (10000, 6). Variables are now: ['mom_var', 'B_var', 'theta_var', 'magnetic_flux_var', 'luminosity_var', 'pressure_var']
Going through DF 7 solving for equation II.15.4, X shape: (10000, 6), y shape: (10000,)
Target variable:  L_rad
Target unit:  Spectral radiance
Bloated X shape to (10000, 8). Variables are now: ['omega_var', 'T_var', 'h_var', 'kb_var', 'c_var', 'pressure_var', 'luminosity_var', 'temperature_var']
Going through DF 8 solving for equation I.41.16, X shape: (10000, 8), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["sqrt(omega_var) * (T_var * omega_var / (3.02957 * c_var)) ^ 1.7062205", "omega_var ^ 1.3064418 / c_var", "sqrt(omega_var - 0.26267505) * ((T_var + c_var + exp(0.72471654 ^ sin(omega_var)) - 2.1369781) / c_var) * (sqrt(kb_var) - 0.34373066) - 0.4556331"]} ...
validated successfully
final expression list:
['sqrt(omega_var) * (T_var * omega_var / (3.02957 * c_var)) ^ 1.7062205', 'omega_var ^ 1.3064418 / c_var', 'sqrt(omega_var - 0.26267505) * ((T_var + c_var + exp(0.72471654 ^ sin(omega_var)) - 2.1369781) / c_var) * (sqrt(kb_var) - 0.34373066) - 0.4556331']
[np.float64(14.01020477246638), np.float64(5.212894999496869), np.float64(13.976069244067205)]
[13, 7, 25]
LLM called. Sending equations and meta info
validating {"expressions": ["(omega_var/c_var)^1.9955536*(0.47249705669771*T_var*kb_var - 0.5644852)/log(h_var - kb_var + temperature_var)", "omega_var^sin(c_var)", "(omega_var/c_var)^1.9955536*(0.47249705669771*T_var*kb_var - 0.5644852)/log(-c_var*kb_var + h_var^2 + temperature_var)"]} ...
validated successfully
final expression list:
['(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log(h_var - kb_var + temperature_var)', 'omega_var ^ sin(c_var)', '(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log((0 - c_var) * kb_var + h_var ^ 2 + temperature_var)']
[np.float64(0.015044843729152662), np.float64(6.495831125999454), np.float64(0.009428802069197648)]
[23, 4, 26]
Valid syntax, but scores too low. Reprompting (Attempt 1)
validating {"expressions": ["(omega_var/c_var)^1.9955536*(0.47249705669771*T_var*kb_var - 0.5644852)/log(h_var + temperature_var)", "(omega_var/c_var)^1.9955536*(0.47249705669771*T_var*kb_var - 0.5644852)/log(temperature_var/h_var)", "omega_var^sin(T_var)"]} ...
validated successfully
final expression list:
['(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log(h_var + temperature_var)', '(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log(temperature_var / h_var)', 'omega_var ^ sin(T_var)']
[np.float64(0.015295627698197081), np.float64(1.4557403969062859), np.float64(11.907556215985673)]
[20, 22, 4]
Valid syntax, but scores too low. Reprompting (Attempt 2)
validating {"expressions": ["(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log(h_var + temperature_var)", "(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log(7.835079251757 * h_var - 6.835079251757 * kb_var + temperature_var)", "(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log(h_var^2 + temperature_var)"]} ...
validated successfully
final expression list:
['(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log(h_var + temperature_var)', '(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log(7.835079251757 * h_var - 6.835079251757 * kb_var + temperature_var)', '(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log(h_var ^ 2 + temperature_var)']
[np.float64(0.015295627698197081), np.float64(0.010936138872755626), np.float64(0.01359514928908562)]
[20, 25, 22]
Valid syntax, but scores too low. Reprompting (Attempt 3)
validating {"expressions": ["(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log(h_var - kb_var + temperature_var)", "(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log(7.835079251757 * h_var - 6.835079251757 * kb_var + temperature_var + 6.78927294288947)", "(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log(-c_var * kb_var + h_var^2 + temperature_var)"]} ...
validated successfully
final expression list:
['(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log(h_var - kb_var + temperature_var)', '(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log(7.835079251757 * h_var - 6.835079251757 * kb_var + temperature_var + 6.78927294288947)', '(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log((0 - c_var) * kb_var + h_var ^ 2 + temperature_var)']
[np.float64(0.015044843729152662), np.float64(0.008772231963046747), np.float64(0.009428802069197648)]
[23, 26, 26]
LLM called. Sending equations and meta info
validating {"expressions": ["(omega_var/c_var)^1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log(h_var^2 - omega_var + temperature_var)", "(omega_var/c_var)^1.9776486 * (T_var * kb_var - 0.87608546) / (2.1302266 * 4.5643435)", "(omega_var/c_var)^1.9955536 * (0.47249705669771 * T_var * kb_var - 0.548978359776552) / log(h_var + temperature_var)"]} ...
validated successfully
final expression list:
['(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.5644852) / log(h_var ^ 2 - omega_var + temperature_var)', '(omega_var / c_var) ^ 1.9776486 * (T_var * kb_var - 0.87608546) / (2.1302266 * 4.5643435)', '(omega_var / c_var) ^ 1.9955536 * (0.47249705669771 * T_var * kb_var - 0.548978359776552) / log(h_var + temperature_var)']
[np.float64(0.010515481119710636), np.float64(0.019717922200263742), np.float64(0.015051885929820555)]
[25, 14, 20]
LLM called. Sending equations and meta info

In [15]:
symbols = sympy.symbols("""
sigma theta1 x1 x2 y1 y2 m1 m2 G z1
z2 m_0 v c x3 y3 mu Nn q1 q2
epsilon r Ef q B m u w r1 r2
z k_spring x t F omega omega_0 n theta2 d1
d2 Int_0 lambd d a p h I1 I2 delta
pr gamma kb n_0 mu_drift Volt mob V1 V2 rho
alpha kappa T1 T2 Pwr p_d y sigma_den chi n_rho
I rho_c_0 mom g_ Jz E_n Bx By Bz k
I_0 beta A_vec x0 x4 x5 x6 x7 x8 x9
""")
(sigma, theta1, x1, x2, y1, y2, m1, m2, G, z1,
z2, m_0, v, c, x3, y3, mu, Nn, q1, q2,
epsilon, r, Ef, q, B, m, u, w, r1, r2,
z, k_spring, x, t, F, omega, omega_0, n, theta2, d1,
d2, Int_0, lambd, d, a, p, h, I1, I2, delta,
pr, gamma, kb, n_0, mu_drift, Volt, mob, V1, V2, rho,
alpha, kappa, T1, T2, Pwr, p_d, y, sigma_den, chi, n_rho,
I, rho_c_0, mom, g_, Jz, E_n, Bx, By, Bz, k,
I_0, beta, A_vec,x0,x4,x5,x6,x7,x8,x9) = symbols

locals_ = {s.name: s for s in symbols}

In [16]:
# creating the core DF 

df_pred=pd.read_csv("best_eqs_all_bonus_unguided.csv")
df_pred=df_pred.iloc[:50,:]
df_original = pd.read_csv("datasets/Feynman/BonusEquations.csv")[["Filename","Formula"]]
df_merged = df_pred.merge(df_original,on="Filename",how='left')
df_merged["Equation"] = df_merged["Formula"].map(lambda f: sympy.sympify(f, locals=locals_))
df_merged["Predicted Equation"] = df_merged["sympy_format"].map(lambda f: sympy.sympify(f, locals=locals_))
df_merged= df_merged[["Filename","Equation","loss","Predicted Equation"]]
df_merged=df_merged.drop_duplicates(subset='Filename').set_index('Filename')
df_merged.drop(df_merged[df_merged['Equation']==sympy.nan].index,inplace=True)

In [17]:
# i want to know how similar these are...
# constants are an issue.. we will try to prove equivalence up to a constant 
pred_eqs = df_merged['Predicted Equation']
orig_eqs = df_merged['Equation']

In [18]:
df_pred.shape

(20, 7)

In [19]:
def check_equality(pred_expr, true_expr, true_varnames=None):
    '''
    used to check if two sympy expressions are "equal".
    equality is defined here as equal upto a constant.
    Works by sampling the true equation and then trying out permutations 
    of the input variables of the candidate solution and obtaining the ratio of the fits. 
    If the ratios are identical, the expressions are equivalent upto a constant.  
    
    '''
    # print("Free symbols in the true expression: ")
    # print(true_expr.free_symbols)
    pred_vars = sorted(pred_expr.free_symbols, key=lambda s: s.name)
    if true_varnames:
        true_vars = [sympy.Symbol(n) for n in true_varnames]
    else:
        true_vars = sorted(true_expr.free_symbols, key=lambda s: s.name)
    # print("variables in the true expression: ")
    print(true_vars)
    if len(pred_vars) != len(true_vars):
        return False
# lambdify
    f_pred = sympy.lambdify(pred_vars, pred_expr, "numpy")
    f_true = sympy.lambdify(true_vars, true_expr, "numpy")
    
# 10 points 
    N_samples = 10
    X = np.random.uniform(1.0, 5.0, (N_samples, len(true_vars)))
    
    # Calculate True Output
    try:
        y_true = f_true(*X.T) # evaluate true function over 10 points. 
    except Exception:
        return False 

    best_perm = None
    
    for perm_indices in itertools.permutations(range(len(true_vars))): # [0,1,2] eg if len is 3
        print(perm_indices) # [0,1,2], [0,2,1]
        try:
            # Reorder columns of X to match this permutation
            X_permuted = X[:, perm_indices]
            
            # Eval prediction
            y_pred = f_pred(*X_permuted.T) # get the fit on y after re-ordering. 
            corr_matrix = np.corrcoef(y_pred, y_true)
            if abs(corr_matrix[0, 1]) > 0.99999:
                best_perm = [true_vars[i] for i in perm_indices]
                break
            
            # Calculate Ratio: y_pred / y_true
            # If equations are equivalent (up to constant), ratio should be identical for all points
            ratio = y_pred / y_true            
            # Check if ratio is constant (sigma is almost 0)
            if np.std(ratio) < 1e-5 and np.isfinite(ratio).all():
                # We found a candidate permutation! 
                # Map the indices back to symbols
                best_perm = [true_vars[i] for i in perm_indices]
                break
                
        except Exception:
            continue

    if best_perm:
        mapper = dict(zip(pred_vars, best_perm)) # make the correct mapping.
        pred_mapped = pred_expr.subs(mapper)
        
        # run simplify for a final sanity check 
        final_ratio = sympy.simplify(pred_mapped / true_expr)
        
        if final_ratio.is_constant():
            return True

    return False

In [20]:
# finally, apply the above onto the dataframe and add the col
df_merged["equivalent"] = df_merged.apply(
    lambda row: check_equality(
        row["Predicted Equation"],   # predicted
        row["Equation"]        # ground truth
    ),
    axis=1
)

[E_n, c, m, theta]
(0, 1, 2, 3)
(0, 1, 3, 2)
(0, 2, 1, 3)
(0, 2, 3, 1)
(0, 3, 1, 2)
(0, 3, 2, 1)
(1, 0, 2, 3)
(1, 0, 3, 2)
(1, 2, 0, 3)
(1, 2, 3, 0)
(1, 3, 0, 2)
(1, 3, 2, 0)
(2, 0, 1, 3)
(2, 0, 3, 1)
(2, 1, 0, 3)
(2, 1, 3, 0)
(2, 3, 0, 1)
(2, 3, 1, 0)
(3, 0, 1, 2)
(3, 0, 2, 1)
(3, 1, 0, 2)
(3, 1, 2, 0)
(3, 2, 0, 1)
(3, 2, 1, 0)
[Volt, d, epsilon, q, y]
[alpha, d, theta1, theta2]
[E_n, L, U, m, r]
[alpha, d, epsilon, q, r]
[alpha, m, omega, p, x, y]
[alpha, beta, c, h, m, omega, omega_0]
[G, H_G, alpha, c, k_f, r]
[G, c, m1, m2, r]
(0, 1, 2, 3, 4)
(0, 1, 2, 4, 3)
(0, 1, 3, 2, 4)
(0, 1, 3, 4, 2)
(0, 1, 4, 2, 3)
(0, 1, 4, 3, 2)
(0, 2, 1, 3, 4)
(0, 2, 1, 4, 3)
(0, 2, 3, 1, 4)
(0, 2, 3, 4, 1)
(0, 2, 4, 1, 3)
(0, 2, 4, 3, 1)
(0, 3, 1, 2, 4)
(0, 3, 1, 4, 2)
(0, 3, 2, 1, 4)
(0, 3, 2, 4, 1)
(0, 3, 4, 1, 2)
(0, 3, 4, 2, 1)
(0, 4, 1, 2, 3)
(0, 4, 1, 3, 2)
(0, 4, 2, 1, 3)
(0, 4, 2, 3, 1)
(0, 4, 3, 1, 2)
(0, 4, 3, 2, 1)
(1, 0, 2, 3, 4)
(1, 0, 2, 4, 3)
(1, 0, 3, 2, 4)
(1, 0, 3, 4, 2)
(1, 0, 4, 2, 3)
(1, 0, 4, 3, 2)
(1, 2, 0, 3, 4)
(1, 2, 0, 4, 3)
(1, 2, 3, 0, 4)
(1, 2, 3, 4, 0)
(1, 2, 4, 0, 3)
(1, 2, 4, 3, 0)
(1, 3, 0, 2, 4)
(1, 3, 0, 4, 2)
(1, 3, 2, 0, 4)
(1, 3, 2, 4, 0)
(1, 3, 4, 0, 2)
(1, 3, 4, 2, 0)
(1, 4, 0, 2, 3)
(1, 4, 0, 3, 2)
(1, 4, 2, 0, 3)
(1, 4, 2, 3, 0)
(1, 4, 3, 0, 2)
(1, 4, 3, 2, 0)
(2, 0, 1, 3, 4)
(2, 0, 1, 4, 3)
(2, 0, 3, 1, 4)
(2, 0, 3, 4, 1)
(2, 0, 4, 1, 3)
(2, 0, 4, 3, 1)
(2, 1, 0, 3, 4)
(2, 1, 0, 4, 3)
(2, 1, 3, 0, 4)
(2, 1, 3, 4, 0)
(2, 1, 4, 0, 3)
(2, 1, 4, 3, 0)
(2, 3, 0, 1, 4)
(2, 3, 0, 4, 1)
(2, 3, 1, 0, 4)
(2, 3, 1, 4, 0)
(2, 3, 4, 0, 1)
(2, 3, 4, 1, 0)
(2, 4, 0, 1, 3)
(2, 4, 0, 3, 1)
(2, 4, 1, 0, 3)
(2, 4, 1, 3, 0)
(2, 4, 3, 0, 1)
(2, 4, 3, 1, 0)
(3, 0, 1, 2, 4)
(3, 0, 1, 4, 2)
(3, 0, 2, 1, 4)
(3, 0, 2, 4, 1)
(3, 0, 4, 1, 2)
(3, 0, 4, 2, 1)
(3, 1, 0, 2, 4)
(3, 1, 0, 4, 2)
(3, 1, 2, 0, 4)
(3, 1, 2, 4, 0)
(3, 1, 4, 0, 2)
(3, 1, 4, 2, 0)
(3, 2, 0, 1, 4)
(3, 2, 0, 4, 1)
(3, 2, 1, 0, 4)
(3, 2, 1, 4, 0)
(3, 2, 4, 0, 1)
(3, 2, 4, 1, 0)
(3, 4, 0, 1, 2)
(3, 4, 0, 2, 1)
(3, 4, 1, 0, 2)
(3, 4, 1, 2, 0)
(3, 4, 2, 0, 1)
(3, 4, 2, 1, 0)
(4, 0, 1, 2, 3)
(4, 0, 1, 3, 2)
(4, 0, 2, 1, 3)
(4, 0, 2, 3, 1)
(4, 0, 3, 1, 2)
(4, 0, 3, 2, 1)
(4, 1, 0, 2, 3)
(4, 1, 0, 3, 2)
(4, 1, 2, 0, 3)
(4, 1, 2, 3, 0)
(4, 1, 3, 0, 2)
(4, 1, 3, 2, 0)
(4, 2, 0, 1, 3)
(4, 2, 0, 3, 1)
(4, 2, 1, 0, 3)
(4, 2, 1, 3, 0)
(4, 2, 3, 0, 1)
(4, 2, 3, 1, 0)
(4, 3, 0, 1, 2)
(4, 3, 0, 2, 1)
(4, 3, 1, 0, 2)
(4, 3, 1, 2, 0)
(4, 3, 2, 0, 1)
(4, 3, 2, 1, 0)
[G, H_G, c, k_f, r]
[E_n, L, k_G, m, theta1, theta2]
[c, omega, theta, v]
[E_n, L, Z_1, Z_2, epsilon, m, q]
[G, d, m1, m2]
(0, 1, 2, 3)
(0, 1, 3, 2)
(0, 2, 1, 3)
(0, 2, 3, 1)
(0, 3, 1, 2)
(0, 3, 2, 1)
(1, 0, 2, 3)
(1, 0, 3, 2)
(1, 2, 0, 3)
(1, 2, 3, 0)
(1, 3, 0, 2)
(1, 3, 2, 0)
(2, 0, 1, 3)
(2, 0, 3, 1)
(2, 1, 0, 3)
(2, 1, 3, 0)
(2, 3, 0, 1)
(2, 3, 1, 0)
(3, 0, 1, 2)
(3, 0, 2, 1)
(3, 1, 0, 2)
(3, 1, 2, 0)
(3, 2, 0, 1)
(3, 2, 1, 0)
[A_vec, Volt, c, m, p, q]
[E_n, Z_1, Z_2, alpha, c, hbar, theta]
(0, 1, 2, 3, 4, 5, 6)
(0, 1, 2, 3, 4, 6, 5)
(0, 1, 2, 3, 5, 4, 6)
(0, 1, 2, 3, 5, 6, 4)
(0, 1, 2, 3, 6, 4, 5)
(0, 1, 2, 3, 6, 5, 4)
(0, 1, 2, 4, 3, 5, 6)
(0, 1, 2, 4, 3, 6, 5)
(0, 1, 2, 4, 5, 3, 6)
(0, 1, 2, 4, 5, 6, 3)
(0, 1, 2, 4, 6, 3, 5)
(0, 1, 2, 4, 6, 5, 3)
(0, 1, 2, 5, 3, 4, 6)
(0, 1, 2, 5, 3, 6, 4)
(0, 1, 2, 5, 4, 3, 6)
(0, 1, 2, 5, 4, 6, 3)
(0, 1, 2, 5, 6, 3, 4)
(0, 1, 2, 5, 6, 4, 3)
(0, 1, 2, 6, 3, 4, 5)
(0, 1, 2, 6, 3, 5, 4)
(0, 1, 2, 6, 4, 3, 5)
(0, 1, 2, 6, 4, 5, 3)
(0, 1, 2, 6, 5, 3, 4)
(0, 1, 2, 6, 5, 4, 3)
(0, 1, 3, 2, 4, 5, 6)
(0, 1, 3, 2, 4, 6, 5)
(0, 1, 3, 2, 5, 4, 6)
(0, 1, 3, 2, 5, 6, 4)
(0, 1, 3, 2, 6, 4, 5)
(0, 1, 3, 2, 6, 5, 4)
(0, 1, 3, 4, 2, 5, 6)
(0, 1, 3, 4, 2, 6, 5)
(0, 1, 3, 4, 5, 2, 6)
(0, 1, 3, 4, 5, 6, 2)
(0, 1, 3, 4, 6, 2, 5)
(0, 1, 3, 4, 6, 5, 2)
(0, 1, 3, 5, 2, 4, 6)
(0, 1, 3, 5, 2, 6, 4)
(0, 1, 3, 5, 4, 2, 6)
(0, 1, 3, 5, 4, 6, 2)
(0, 1, 3, 5, 6, 2, 4)
(0, 1, 3, 5, 6, 4, 2)
(0, 1, 3, 6, 2, 4, 5)
(0, 1, 3, 6, 2, 5, 4)
(0, 1, 3, 6, 4, 2, 5)
(0, 1, 3, 6, 4, 5, 2)
(0, 1, 3, 6, 5, 2, 4)
(0, 1, 3, 6, 5, 4, 2)
(0, 1, 4, 2, 3, 5, 6)
(0, 1, 4, 2, 3, 6, 5)
(0, 1, 4, 2, 5, 3, 6)
(0, 1, 4, 2, 5, 6, 3)
(0, 1, 4, 2, 6, 3, 5)
(0, 1, 4, 2, 6, 5, 3)
(0, 1, 4, 3, 2, 5, 6)
(0, 1, 4, 3, 2, 6, 5)
(0, 1, 4, 3, 5, 2, 6)
(0, 1, 4, 3, 5, 6, 2)
(0, 1, 4, 3, 6, 2, 5)
(0, 1, 4, 3, 6, 5, 2)
(0, 1, 4, 5, 2, 3, 6)
(0, 1, 4, 5, 2, 6, 3)
(0, 1, 4, 5, 3, 2, 6)
(0, 1, 4, 5, 3, 6, 2)
(0, 1, 4, 5, 6, 2, 3)
(0, 1, 4, 5, 6, 3, 2)
(0, 1, 4, 6, 2, 3, 5)
(0, 1, 4, 6, 2, 5, 3)
(0, 1, 4, 6, 3, 2, 5)
(0, 1, 4, 6, 3, 5, 2)
(0, 1, 4, 6, 5, 2, 3)
(0, 1, 4, 6, 5, 3, 2)
(0, 1, 5, 2, 3, 4, 6)
(0, 1, 5, 2, 3, 6, 4)
(0, 1, 5, 2, 4, 3, 6)
(0, 1, 5, 2, 4, 6, 3)
(0, 1, 5, 2, 6, 3, 4)
(0, 1, 5, 2, 6, 4, 3)
(0, 1, 5, 3, 2, 4, 6)
(0, 1, 5, 3, 2, 6, 4)
(0, 1, 5, 3, 4, 2, 6)
(0, 1, 5, 3, 4, 6, 2)
(0, 1, 5, 3, 6, 2, 4)
(0, 1, 5, 3, 6, 4, 2)
(0, 1, 5, 4, 2, 3, 6)
(0, 1, 5, 4, 2, 6, 3)
(0, 1, 5, 4, 3, 2, 6)
(0, 1, 5, 4, 3, 6, 2)
(0, 1, 5, 4, 6, 2, 3)
(0, 1, 5, 4, 6, 3, 2)
(0, 1, 5, 6, 2, 3, 4)
(0, 1, 5, 6, 2, 4, 3)
(0, 1, 5, 6, 3, 2, 4)
(0, 1, 5, 6, 3, 4, 2)
(0, 1, 5, 6, 4, 2, 3)
(0, 1, 5, 6, 4, 3, 2)
(0, 1, 6, 2, 3, 4, 5)
(0, 1, 6, 2, 3, 5, 4)
(0, 1, 6, 2, 4, 3, 5)
(0, 1, 6, 2, 4, 5, 3)
(0, 1, 6, 2, 5, 3, 4)
(0, 1, 6, 2, 5, 4, 3)
(0, 1, 6, 3, 2, 4, 5)
(0, 1, 6, 3, 2, 5, 4)
(0, 1, 6, 3, 4, 2, 5)
(0, 1, 6, 3, 4, 5, 2)
(0, 1, 6, 3, 5, 2, 4)
(0, 1, 6, 3, 5, 4, 2)
(0, 1, 6, 4, 2, 3, 5)
(0, 1, 6, 4, 2, 5, 3)
(0, 1, 6, 4, 3, 2, 5)
(0, 1, 6, 4, 3, 5, 2)
(0, 1, 6, 4, 5, 2, 3)
(0, 1, 6, 4, 5, 3, 2)
(0, 1, 6, 5, 2, 3, 4)
(0, 1, 6, 5, 2, 4, 3)
(0, 1, 6, 5, 3, 2, 4)
(0, 1, 6, 5, 3, 4, 2)
(0, 1, 6, 5, 4, 2, 3)
(0, 1, 6, 5, 4, 3, 2)
(0, 2, 1, 3, 4, 5, 6)
(0, 2, 1, 3, 4, 6, 5)
(0, 2, 1, 3, 5, 4, 6)
(0, 2, 1, 3, 5, 6, 4)
(0, 2, 1, 3, 6, 4, 5)
(0, 2, 1, 3, 6, 5, 4)
(0, 2, 1, 4, 3, 5, 6)
(0, 2, 1, 4, 3, 6, 5)
(0, 2, 1, 4, 5, 3, 6)
(0, 2, 1, 4, 5, 6, 3)
(0, 2, 1, 4, 6, 3, 5)
(0, 2, 1, 4, 6, 5, 3)
(0, 2, 1, 5, 3, 4, 6)
(0, 2, 1, 5, 3, 6, 4)
(0, 2, 1, 5, 4, 3, 6)
(0, 2, 1, 5, 4, 6, 3)
(0, 2, 1, 5, 6, 3, 4)
(0, 2, 1, 5, 6, 4, 3)
(0, 2, 1, 6, 3, 4, 5)
(0, 2, 1, 6, 3, 5, 4)
(0, 2, 1, 6, 4, 3, 5)
(0, 2, 1, 6, 4, 5, 3)
(0, 2, 1, 6, 5, 3, 4)
(0, 2, 1, 6, 5, 4, 3)
(0, 2, 3, 1, 4, 5, 6)
(0, 2, 3, 1, 4, 6, 5)
(0, 2, 3, 1, 5, 4, 6)
(0, 2, 3, 1, 5, 6, 4)
(0, 2, 3, 1, 6, 4, 5)
(0, 2, 3, 1, 6, 5, 4)
(0, 2, 3, 4, 1, 5, 6)
(0, 2, 3, 4, 1, 6, 5)
(0, 2, 3, 4, 5, 1, 6)
(0, 2, 3, 4, 5, 6, 1)
(0, 2, 3, 4, 6, 1, 5)
(0, 2, 3, 4, 6, 5, 1)
(0, 2, 3, 5, 1, 4, 6)
(0, 2, 3, 5, 1, 6, 4)
(0, 2, 3, 5, 4, 1, 6)
(0, 2, 3, 5, 4, 6, 1)
(0, 2, 3, 5, 6, 1, 4)
(0, 2, 3, 5, 6, 4, 1)
(0, 2, 3, 6, 1, 4, 5)
(0, 2, 3, 6, 1, 5, 4)
(0, 2, 3, 6, 4, 1, 5)
(0, 2, 3, 6, 4, 5, 1)
(0, 2, 3, 6, 5, 1, 4)
(0, 2, 3, 6, 5, 4, 1)
(0, 2, 4, 1, 3, 5, 6)
(0, 2, 4, 1, 3, 6, 5)
(0, 2, 4, 1, 5, 3, 6)
(0, 2, 4, 1, 5, 6, 3)
(0, 2, 4, 1, 6, 3, 5)
(0, 2, 4, 1, 6, 5, 3)
(0, 2, 4, 3, 1, 5, 6)
(0, 2, 4, 3, 1, 6, 5)
(0, 2, 4, 3, 5, 1, 6)
(0, 2, 4, 3, 5, 6, 1)
(0, 2, 4, 3, 6, 1, 5)
(0, 2, 4, 3, 6, 5, 1)
(0, 2, 4, 5, 1, 3, 6)
(0, 2, 4, 5, 1, 6, 3)
(0, 2, 4, 5, 3, 1, 6)
(0, 2, 4, 5, 3, 6, 1)
(0, 2, 4, 5, 6, 1, 3)
(0, 2, 4, 5, 6, 3, 1)
(0, 2, 4, 6, 1, 3, 5)
(0, 2, 4, 6, 1, 5, 3)
(0, 2, 4, 6, 3, 1, 5)
(0, 2, 4, 6, 3, 5, 1)
(0, 2, 4, 6, 5, 1, 3)
(0, 2, 4, 6, 5, 3, 1)
(0, 2, 5, 1, 3, 4, 6)
(0, 2, 5, 1, 3, 6, 4)
(0, 2, 5, 1, 4, 3, 6)
(0, 2, 5, 1, 4, 6, 3)
(0, 2, 5, 1, 6, 3, 4)
(0, 2, 5, 1, 6, 4, 3)
(0, 2, 5, 3, 1, 4, 6)
(0, 2, 5, 3, 1, 6, 4)
(0, 2, 5, 3, 4, 1, 6)
(0, 2, 5, 3, 4, 6, 1)
(0, 2, 5, 3, 6, 1, 4)
(0, 2, 5, 3, 6, 4, 1)
(0, 2, 5, 4, 1, 3, 6)
(0, 2, 5, 4, 1, 6, 3)
(0, 2, 5, 4, 3, 1, 6)
(0, 2, 5, 4, 3, 6, 1)
(0, 2, 5, 4, 6, 1, 3)
(0, 2, 5, 4, 6, 3, 1)
(0, 2, 5, 6, 1, 3, 4)
(0, 2, 5, 6, 1, 4, 3)
(0, 2, 5, 6, 3, 1, 4)
(0, 2, 5, 6, 3, 4, 1)
(0, 2, 5, 6, 4, 1, 3)
(0, 2, 5, 6, 4, 3, 1)
(0, 2, 6, 1, 3, 4, 5)
(0, 2, 6, 1, 3, 5, 4)
(0, 2, 6, 1, 4, 3, 5)
(0, 2, 6, 1, 4, 5, 3)
(0, 2, 6, 1, 5, 3, 4)
(0, 2, 6, 1, 5, 4, 3)
(0, 2, 6, 3, 1, 4, 5)
(0, 2, 6, 3, 1, 5, 4)
(0, 2, 6, 3, 4, 1, 5)
(0, 2, 6, 3, 4, 5, 1)
(0, 2, 6, 3, 5, 1, 4)
(0, 2, 6, 3, 5, 4, 1)
(0, 2, 6, 4, 1, 3, 5)
(0, 2, 6, 4, 1, 5, 3)
(0, 2, 6, 4, 3, 1, 5)
(0, 2, 6, 4, 3, 5, 1)
(0, 2, 6, 4, 5, 1, 3)
(0, 2, 6, 4, 5, 3, 1)
(0, 2, 6, 5, 1, 3, 4)
(0, 2, 6, 5, 1, 4, 3)
(0, 2, 6, 5, 3, 1, 4)
(0, 2, 6, 5, 3, 4, 1)
(0, 2, 6, 5, 4, 1, 3)
(0, 2, 6, 5, 4, 3, 1)
(0, 3, 1, 2, 4, 5, 6)
(0, 3, 1, 2, 4, 6, 5)
(0, 3, 1, 2, 5, 4, 6)
(0, 3, 1, 2, 5, 6, 4)
(0, 3, 1, 2, 6, 4, 5)
(0, 3, 1, 2, 6, 5, 4)
(0, 3, 1, 4, 2, 5, 6)
(0, 3, 1, 4, 2, 6, 5)
(0, 3, 1, 4, 5, 2, 6)
(0, 3, 1, 4, 5, 6, 2)
(0, 3, 1, 4, 6, 2, 5)
(0, 3, 1, 4, 6, 5, 2)
(0, 3, 1, 5, 2, 4, 6)
(0, 3, 1, 5, 2, 6, 4)
(0, 3, 1, 5, 4, 2, 6)
(0, 3, 1, 5, 4, 6, 2)
(0, 3, 1, 5, 6, 2, 4)
(0, 3, 1, 5, 6, 4, 2)
(0, 3, 1, 6, 2, 4, 5)
(0, 3, 1, 6, 2, 5, 4)
(0, 3, 1, 6, 4, 2, 5)
(0, 3, 1, 6, 4, 5, 2)
(0, 3, 1, 6, 5, 2, 4)
(0, 3, 1, 6, 5, 4, 2)
(0, 3, 2, 1, 4, 5, 6)
(0, 3, 2, 1, 4, 6, 5)
(0, 3, 2, 1, 5, 4, 6)
(0, 3, 2, 1, 5, 6, 4)
(0, 3, 2, 1, 6, 4, 5)
(0, 3, 2, 1, 6, 5, 4)
(0, 3, 2, 4, 1, 5, 6)
(0, 3, 2, 4, 1, 6, 5)
(0, 3, 2, 4, 5, 1, 6)
(0, 3, 2, 4, 5, 6, 1)
(0, 3, 2, 4, 6, 1, 5)
(0, 3, 2, 4, 6, 5, 1)
(0, 3, 2, 5, 1, 4, 6)
(0, 3, 2, 5, 1, 6, 4)
(0, 3, 2, 5, 4, 1, 6)
(0, 3, 2, 5, 4, 6, 1)
(0, 3, 2, 5, 6, 1, 4)
(0, 3, 2, 5, 6, 4, 1)
(0, 3, 2, 6, 1, 4, 5)
(0, 3, 2, 6, 1, 5, 4)
(0, 3, 2, 6, 4, 1, 5)
(0, 3, 2, 6, 4, 5, 1)
(0, 3, 2, 6, 5, 1, 4)
(0, 3, 2, 6, 5, 4, 1)
(0, 3, 4, 1, 2, 5, 6)
(0, 3, 4, 1, 2, 6, 5)
(0, 3, 4, 1, 5, 2, 6)
(0, 3, 4, 1, 5, 6, 2)
(0, 3, 4, 1, 6, 2, 5)
(0, 3, 4, 1, 6, 5, 2)
(0, 3, 4, 2, 1, 5, 6)
(0, 3, 4, 2, 1, 6, 5)
(0, 3, 4, 2, 5, 1, 6)
(0, 3, 4, 2, 5, 6, 1)
(0, 3, 4, 2, 6, 1, 5)
(0, 3, 4, 2, 6, 5, 1)
(0, 3, 4, 5, 1, 2, 6)
(0, 3, 4, 5, 1, 6, 2)
(0, 3, 4, 5, 2, 1, 6)
(0, 3, 4, 5, 2, 6, 1)
(0, 3, 4, 5, 6, 1, 2)
(0, 3, 4, 5, 6, 2, 1)
(0, 3, 4, 6, 1, 2, 5)
(0, 3, 4, 6, 1, 5, 2)
(0, 3, 4, 6, 2, 1, 5)
(0, 3, 4, 6, 2, 5, 1)
(0, 3, 4, 6, 5, 1, 2)
(0, 3, 4, 6, 5, 2, 1)
(0, 3, 5, 1, 2, 4, 6)
(0, 3, 5, 1, 2, 6, 4)
(0, 3, 5, 1, 4, 2, 6)
(0, 3, 5, 1, 4, 6, 2)
(0, 3, 5, 1, 6, 2, 4)
(0, 3, 5, 1, 6, 4, 2)
(0, 3, 5, 2, 1, 4, 6)
(0, 3, 5, 2, 1, 6, 4)
(0, 3, 5, 2, 4, 1, 6)
(0, 3, 5, 2, 4, 6, 1)
(0, 3, 5, 2, 6, 1, 4)
(0, 3, 5, 2, 6, 4, 1)
(0, 3, 5, 4, 1, 2, 6)
(0, 3, 5, 4, 1, 6, 2)
(0, 3, 5, 4, 2, 1, 6)
(0, 3, 5, 4, 2, 6, 1)
(0, 3, 5, 4, 6, 1, 2)
(0, 3, 5, 4, 6, 2, 1)
(0, 3, 5, 6, 1, 2, 4)
(0, 3, 5, 6, 1, 4, 2)
(0, 3, 5, 6, 2, 1, 4)
(0, 3, 5, 6, 2, 4, 1)
(0, 3, 5, 6, 4, 1, 2)
(0, 3, 5, 6, 4, 2, 1)
(0, 3, 6, 1, 2, 4, 5)
(0, 3, 6, 1, 2, 5, 4)
(0, 3, 6, 1, 4, 2, 5)
(0, 3, 6, 1, 4, 5, 2)
(0, 3, 6, 1, 5, 2, 4)
(0, 3, 6, 1, 5, 4, 2)
(0, 3, 6, 2, 1, 4, 5)
(0, 3, 6, 2, 1, 5, 4)
(0, 3, 6, 2, 4, 1, 5)
(0, 3, 6, 2, 4, 5, 1)
(0, 3, 6, 2, 5, 1, 4)
(0, 3, 6, 2, 5, 4, 1)
(0, 3, 6, 4, 1, 2, 5)
(0, 3, 6, 4, 1, 5, 2)
(0, 3, 6, 4, 2, 1, 5)
(0, 3, 6, 4, 2, 5, 1)
(0, 3, 6, 4, 5, 1, 2)
(0, 3, 6, 4, 5, 2, 1)
(0, 3, 6, 5, 1, 2, 4)
(0, 3, 6, 5, 1, 4, 2)
(0, 3, 6, 5, 2, 1, 4)
(0, 3, 6, 5, 2, 4, 1)
(0, 3, 6, 5, 4, 1, 2)
(0, 3, 6, 5, 4, 2, 1)
(0, 4, 1, 2, 3, 5, 6)
(0, 4, 1, 2, 3, 6, 5)
(0, 4, 1, 2, 5, 3, 6)
(0, 4, 1, 2, 5, 6, 3)
(0, 4, 1, 2, 6, 3, 5)
(0, 4, 1, 2, 6, 5, 3)
(0, 4, 1, 3, 2, 5, 6)
(0, 4, 1, 3, 2, 6, 5)
(0, 4, 1, 3, 5, 2, 6)
(0, 4, 1, 3, 5, 6, 2)
(0, 4, 1, 3, 6, 2, 5)
(0, 4, 1, 3, 6, 5, 2)
(0, 4, 1, 5, 2, 3, 6)
(0, 4, 1, 5, 2, 6, 3)
(0, 4, 1, 5, 3, 2, 6)
(0, 4, 1, 5, 3, 6, 2)
(0, 4, 1, 5, 6, 2, 3)
(0, 4, 1, 5, 6, 3, 2)
(0, 4, 1, 6, 2, 3, 5)
(0, 4, 1, 6, 2, 5, 3)
(0, 4, 1, 6, 3, 2, 5)
(0, 4, 1, 6, 3, 5, 2)
(0, 4, 1, 6, 5, 2, 3)
(0, 4, 1, 6, 5, 3, 2)
(0, 4, 2, 1, 3, 5, 6)
(0, 4, 2, 1, 3, 6, 5)
(0, 4, 2, 1, 5, 3, 6)
(0, 4, 2, 1, 5, 6, 3)
(0, 4, 2, 1, 6, 3, 5)
(0, 4, 2, 1, 6, 5, 3)
(0, 4, 2, 3, 1, 5, 6)
(0, 4, 2, 3, 1, 6, 5)
(0, 4, 2, 3, 5, 1, 6)
(0, 4, 2, 3, 5, 6, 1)
(0, 4, 2, 3, 6, 1, 5)
(0, 4, 2, 3, 6, 5, 1)
(0, 4, 2, 5, 1, 3, 6)
(0, 4, 2, 5, 1, 6, 3)
(0, 4, 2, 5, 3, 1, 6)
(0, 4, 2, 5, 3, 6, 1)
(0, 4, 2, 5, 6, 1, 3)
(0, 4, 2, 5, 6, 3, 1)
(0, 4, 2, 6, 1, 3, 5)
(0, 4, 2, 6, 1, 5, 3)
(0, 4, 2, 6, 3, 1, 5)
(0, 4, 2, 6, 3, 5, 1)
(0, 4, 2, 6, 5, 1, 3)
(0, 4, 2, 6, 5, 3, 1)
(0, 4, 3, 1, 2, 5, 6)
(0, 4, 3, 1, 2, 6, 5)
(0, 4, 3, 1, 5, 2, 6)
(0, 4, 3, 1, 5, 6, 2)
(0, 4, 3, 1, 6, 2, 5)
(0, 4, 3, 1, 6, 5, 2)
(0, 4, 3, 2, 1, 5, 6)
(0, 4, 3, 2, 1, 6, 5)
(0, 4, 3, 2, 5, 1, 6)
(0, 4, 3, 2, 5, 6, 1)
(0, 4, 3, 2, 6, 1, 5)
(0, 4, 3, 2, 6, 5, 1)
(0, 4, 3, 5, 1, 2, 6)
(0, 4, 3, 5, 1, 6, 2)
(0, 4, 3, 5, 2, 1, 6)
(0, 4, 3, 5, 2, 6, 1)
(0, 4, 3, 5, 6, 1, 2)
(0, 4, 3, 5, 6, 2, 1)
(0, 4, 3, 6, 1, 2, 5)
(0, 4, 3, 6, 1, 5, 2)
(0, 4, 3, 6, 2, 1, 5)
(0, 4, 3, 6, 2, 5, 1)
(0, 4, 3, 6, 5, 1, 2)
(0, 4, 3, 6, 5, 2, 1)
(0, 4, 5, 1, 2, 3, 6)
(0, 4, 5, 1, 2, 6, 3)
(0, 4, 5, 1, 3, 2, 6)
(0, 4, 5, 1, 3, 6, 2)
(0, 4, 5, 1, 6, 2, 3)
(0, 4, 5, 1, 6, 3, 2)
(0, 4, 5, 2, 1, 3, 6)
(0, 4, 5, 2, 1, 6, 3)
(0, 4, 5, 2, 3, 1, 6)
(0, 4, 5, 2, 3, 6, 1)
(0, 4, 5, 2, 6, 1, 3)
(0, 4, 5, 2, 6, 3, 1)
(0, 4, 5, 3, 1, 2, 6)
(0, 4, 5, 3, 1, 6, 2)
(0, 4, 5, 3, 2, 1, 6)
(0, 4, 5, 3, 2, 6, 1)
(0, 4, 5, 3, 6, 1, 2)
(0, 4, 5, 3, 6, 2, 1)
(0, 4, 5, 6, 1, 2, 3)
(0, 4, 5, 6, 1, 3, 2)
(0, 4, 5, 6, 2, 1, 3)
(0, 4, 5, 6, 2, 3, 1)
(0, 4, 5, 6, 3, 1, 2)
(0, 4, 5, 6, 3, 2, 1)
(0, 4, 6, 1, 2, 3, 5)
(0, 4, 6, 1, 2, 5, 3)
(0, 4, 6, 1, 3, 2, 5)
(0, 4, 6, 1, 3, 5, 2)
(0, 4, 6, 1, 5, 2, 3)
(0, 4, 6, 1, 5, 3, 2)
(0, 4, 6, 2, 1, 3, 5)
(0, 4, 6, 2, 1, 5, 3)
(0, 4, 6, 2, 3, 1, 5)
(0, 4, 6, 2, 3, 5, 1)
(0, 4, 6, 2, 5, 1, 3)
(0, 4, 6, 2, 5, 3, 1)
(0, 4, 6, 3, 1, 2, 5)
(0, 4, 6, 3, 1, 5, 2)
(0, 4, 6, 3, 2, 1, 5)
(0, 4, 6, 3, 2, 5, 1)
(0, 4, 6, 3, 5, 1, 2)
(0, 4, 6, 3, 5, 2, 1)
(0, 4, 6, 5, 1, 2, 3)
(0, 4, 6, 5, 1, 3, 2)
(0, 4, 6, 5, 2, 1, 3)
(0, 4, 6, 5, 2, 3, 1)
(0, 4, 6, 5, 3, 1, 2)
(0, 4, 6, 5, 3, 2, 1)
(0, 5, 1, 2, 3, 4, 6)
(0, 5, 1, 2, 3, 6, 4)
(0, 5, 1, 2, 4, 3, 6)
(0, 5, 1, 2, 4, 6, 3)
(0, 5, 1, 2, 6, 3, 4)
(0, 5, 1, 2, 6, 4, 3)
(0, 5, 1, 3, 2, 4, 6)
(0, 5, 1, 3, 2, 6, 4)
(0, 5, 1, 3, 4, 2, 6)
(0, 5, 1, 3, 4, 6, 2)
(0, 5, 1, 3, 6, 2, 4)
(0, 5, 1, 3, 6, 4, 2)
(0, 5, 1, 4, 2, 3, 6)
(0, 5, 1, 4, 2, 6, 3)
(0, 5, 1, 4, 3, 2, 6)
(0, 5, 1, 4, 3, 6, 2)
(0, 5, 1, 4, 6, 2, 3)
(0, 5, 1, 4, 6, 3, 2)
(0, 5, 1, 6, 2, 3, 4)
(0, 5, 1, 6, 2, 4, 3)
(0, 5, 1, 6, 3, 2, 4)
(0, 5, 1, 6, 3, 4, 2)
(0, 5, 1, 6, 4, 2, 3)
(0, 5, 1, 6, 4, 3, 2)
(0, 5, 2, 1, 3, 4, 6)
(0, 5, 2, 1, 3, 6, 4)
(0, 5, 2, 1, 4, 3, 6)
(0, 5, 2, 1, 4, 6, 3)
(0, 5, 2, 1, 6, 3, 4)
(0, 5, 2, 1, 6, 4, 3)
(0, 5, 2, 3, 1, 4, 6)
(0, 5, 2, 3, 1, 6, 4)
(0, 5, 2, 3, 4, 1, 6)
(0, 5, 2, 3, 4, 6, 1)
(0, 5, 2, 3, 6, 1, 4)
(0, 5, 2, 3, 6, 4, 1)
(0, 5, 2, 4, 1, 3, 6)
(0, 5, 2, 4, 1, 6, 3)
(0, 5, 2, 4, 3, 1, 6)
(0, 5, 2, 4, 3, 6, 1)
(0, 5, 2, 4, 6, 1, 3)
(0, 5, 2, 4, 6, 3, 1)
(0, 5, 2, 6, 1, 3, 4)
(0, 5, 2, 6, 1, 4, 3)
(0, 5, 2, 6, 3, 1, 4)
(0, 5, 2, 6, 3, 4, 1)
(0, 5, 2, 6, 4, 1, 3)
(0, 5, 2, 6, 4, 3, 1)
(0, 5, 3, 1, 2, 4, 6)
(0, 5, 3, 1, 2, 6, 4)
(0, 5, 3, 1, 4, 2, 6)
(0, 5, 3, 1, 4, 6, 2)
(0, 5, 3, 1, 6, 2, 4)
(0, 5, 3, 1, 6, 4, 2)
(0, 5, 3, 2, 1, 4, 6)
(0, 5, 3, 2, 1, 6, 4)
(0, 5, 3, 2, 4, 1, 6)
(0, 5, 3, 2, 4, 6, 1)
(0, 5, 3, 2, 6, 1, 4)
(0, 5, 3, 2, 6, 4, 1)
(0, 5, 3, 4, 1, 2, 6)
(0, 5, 3, 4, 1, 6, 2)
(0, 5, 3, 4, 2, 1, 6)
(0, 5, 3, 4, 2, 6, 1)
(0, 5, 3, 4, 6, 1, 2)
(0, 5, 3, 4, 6, 2, 1)
(0, 5, 3, 6, 1, 2, 4)
(0, 5, 3, 6, 1, 4, 2)
(0, 5, 3, 6, 2, 1, 4)
(0, 5, 3, 6, 2, 4, 1)
(0, 5, 3, 6, 4, 1, 2)
(0, 5, 3, 6, 4, 2, 1)
(0, 5, 4, 1, 2, 3, 6)
(0, 5, 4, 1, 2, 6, 3)
(0, 5, 4, 1, 3, 2, 6)
(0, 5, 4, 1, 3, 6, 2)
(0, 5, 4, 1, 6, 2, 3)
(0, 5, 4, 1, 6, 3, 2)
(0, 5, 4, 2, 1, 3, 6)
(0, 5, 4, 2, 1, 6, 3)
(0, 5, 4, 2, 3, 1, 6)
(0, 5, 4, 2, 3, 6, 1)
(0, 5, 4, 2, 6, 1, 3)
(0, 5, 4, 2, 6, 3, 1)
(0, 5, 4, 3, 1, 2, 6)
(0, 5, 4, 3, 1, 6, 2)
(0, 5, 4, 3, 2, 1, 6)
(0, 5, 4, 3, 2, 6, 1)
(0, 5, 4, 3, 6, 1, 2)
(0, 5, 4, 3, 6, 2, 1)
(0, 5, 4, 6, 1, 2, 3)
(0, 5, 4, 6, 1, 3, 2)
(0, 5, 4, 6, 2, 1, 3)
(0, 5, 4, 6, 2, 3, 1)
(0, 5, 4, 6, 3, 1, 2)
(0, 5, 4, 6, 3, 2, 1)
(0, 5, 6, 1, 2, 3, 4)
(0, 5, 6, 1, 2, 4, 3)
(0, 5, 6, 1, 3, 2, 4)
(0, 5, 6, 1, 3, 4, 2)
(0, 5, 6, 1, 4, 2, 3)
(0, 5, 6, 1, 4, 3, 2)
(0, 5, 6, 2, 1, 3, 4)
(0, 5, 6, 2, 1, 4, 3)
(0, 5, 6, 2, 3, 1, 4)
(0, 5, 6, 2, 3, 4, 1)
(0, 5, 6, 2, 4, 1, 3)
(0, 5, 6, 2, 4, 3, 1)
(0, 5, 6, 3, 1, 2, 4)
(0, 5, 6, 3, 1, 4, 2)
(0, 5, 6, 3, 2, 1, 4)
(0, 5, 6, 3, 2, 4, 1)
(0, 5, 6, 3, 4, 1, 2)
(0, 5, 6, 3, 4, 2, 1)
(0, 5, 6, 4, 1, 2, 3)
(0, 5, 6, 4, 1, 3, 2)
(0, 5, 6, 4, 2, 1, 3)
(0, 5, 6, 4, 2, 3, 1)
(0, 5, 6, 4, 3, 1, 2)
(0, 5, 6, 4, 3, 2, 1)
(0, 6, 1, 2, 3, 4, 5)
(0, 6, 1, 2, 3, 5, 4)
(0, 6, 1, 2, 4, 3, 5)
(0, 6, 1, 2, 4, 5, 3)
(0, 6, 1, 2, 5, 3, 4)
(0, 6, 1, 2, 5, 4, 3)
(0, 6, 1, 3, 2, 4, 5)
(0, 6, 1, 3, 2, 5, 4)
(0, 6, 1, 3, 4, 2, 5)
(0, 6, 1, 3, 4, 5, 2)
(0, 6, 1, 3, 5, 2, 4)
(0, 6, 1, 3, 5, 4, 2)
(0, 6, 1, 4, 2, 3, 5)
(0, 6, 1, 4, 2, 5, 3)
(0, 6, 1, 4, 3, 2, 5)
(0, 6, 1, 4, 3, 5, 2)
(0, 6, 1, 4, 5, 2, 3)
(0, 6, 1, 4, 5, 3, 2)
(0, 6, 1, 5, 2, 3, 4)
(0, 6, 1, 5, 2, 4, 3)
(0, 6, 1, 5, 3, 2, 4)
(0, 6, 1, 5, 3, 4, 2)
(0, 6, 1, 5, 4, 2, 3)
(0, 6, 1, 5, 4, 3, 2)
(0, 6, 2, 1, 3, 4, 5)
(0, 6, 2, 1, 3, 5, 4)
(0, 6, 2, 1, 4, 3, 5)
(0, 6, 2, 1, 4, 5, 3)
(0, 6, 2, 1, 5, 3, 4)
(0, 6, 2, 1, 5, 4, 3)
(0, 6, 2, 3, 1, 4, 5)
(0, 6, 2, 3, 1, 5, 4)
(0, 6, 2, 3, 4, 1, 5)
(0, 6, 2, 3, 4, 5, 1)
(0, 6, 2, 3, 5, 1, 4)
(0, 6, 2, 3, 5, 4, 1)
(0, 6, 2, 4, 1, 3, 5)
(0, 6, 2, 4, 1, 5, 3)
(0, 6, 2, 4, 3, 1, 5)
(0, 6, 2, 4, 3, 5, 1)
(0, 6, 2, 4, 5, 1, 3)
(0, 6, 2, 4, 5, 3, 1)
(0, 6, 2, 5, 1, 3, 4)
(0, 6, 2, 5, 1, 4, 3)
(0, 6, 2, 5, 3, 1, 4)
(0, 6, 2, 5, 3, 4, 1)
(0, 6, 2, 5, 4, 1, 3)
(0, 6, 2, 5, 4, 3, 1)
(0, 6, 3, 1, 2, 4, 5)
(0, 6, 3, 1, 2, 5, 4)
(0, 6, 3, 1, 4, 2, 5)
(0, 6, 3, 1, 4, 5, 2)
(0, 6, 3, 1, 5, 2, 4)
(0, 6, 3, 1, 5, 4, 2)
(0, 6, 3, 2, 1, 4, 5)
(0, 6, 3, 2, 1, 5, 4)
(0, 6, 3, 2, 4, 1, 5)
(0, 6, 3, 2, 4, 5, 1)
(0, 6, 3, 2, 5, 1, 4)
(0, 6, 3, 2, 5, 4, 1)
(0, 6, 3, 4, 1, 2, 5)
(0, 6, 3, 4, 1, 5, 2)
(0, 6, 3, 4, 2, 1, 5)
(0, 6, 3, 4, 2, 5, 1)
(0, 6, 3, 4, 5, 1, 2)
(0, 6, 3, 4, 5, 2, 1)
(0, 6, 3, 5, 1, 2, 4)
(0, 6, 3, 5, 1, 4, 2)
(0, 6, 3, 5, 2, 1, 4)
(0, 6, 3, 5, 2, 4, 1)
(0, 6, 3, 5, 4, 1, 2)
(0, 6, 3, 5, 4, 2, 1)
(0, 6, 4, 1, 2, 3, 5)
(0, 6, 4, 1, 2, 5, 3)
(0, 6, 4, 1, 3, 2, 5)
(0, 6, 4, 1, 3, 5, 2)
(0, 6, 4, 1, 5, 2, 3)
(0, 6, 4, 1, 5, 3, 2)
(0, 6, 4, 2, 1, 3, 5)
(0, 6, 4, 2, 1, 5, 3)
(0, 6, 4, 2, 3, 1, 5)
(0, 6, 4, 2, 3, 5, 1)
(0, 6, 4, 2, 5, 1, 3)
(0, 6, 4, 2, 5, 3, 1)
(0, 6, 4, 3, 1, 2, 5)
(0, 6, 4, 3, 1, 5, 2)
(0, 6, 4, 3, 2, 1, 5)
(0, 6, 4, 3, 2, 5, 1)
(0, 6, 4, 3, 5, 1, 2)
(0, 6, 4, 3, 5, 2, 1)
(0, 6, 4, 5, 1, 2, 3)
(0, 6, 4, 5, 1, 3, 2)
(0, 6, 4, 5, 2, 1, 3)
(0, 6, 4, 5, 2, 3, 1)
(0, 6, 4, 5, 3, 1, 2)
(0, 6, 4, 5, 3, 2, 1)
(0, 6, 5, 1, 2, 3, 4)
(0, 6, 5, 1, 2, 4, 3)
(0, 6, 5, 1, 3, 2, 4)
(0, 6, 5, 1, 3, 4, 2)
(0, 6, 5, 1, 4, 2, 3)
(0, 6, 5, 1, 4, 3, 2)
(0, 6, 5, 2, 1, 3, 4)
(0, 6, 5, 2, 1, 4, 3)
(0, 6, 5, 2, 3, 1, 4)
(0, 6, 5, 2, 3, 4, 1)
(0, 6, 5, 2, 4, 1, 3)
(0, 6, 5, 2, 4, 3, 1)
(0, 6, 5, 3, 1, 2, 4)
(0, 6, 5, 3, 1, 4, 2)
(0, 6, 5, 3, 2, 1, 4)
(0, 6, 5, 3, 2, 4, 1)
(0, 6, 5, 3, 4, 1, 2)
(0, 6, 5, 3, 4, 2, 1)
(0, 6, 5, 4, 1, 2, 3)
(0, 6, 5, 4, 1, 3, 2)
(0, 6, 5, 4, 2, 1, 3)
(0, 6, 5, 4, 2, 3, 1)
(0, 6, 5, 4, 3, 1, 2)
(0, 6, 5, 4, 3, 2, 1)
(1, 0, 2, 3, 4, 5, 6)
(1, 0, 2, 3, 4, 6, 5)
(1, 0, 2, 3, 5, 4, 6)
(1, 0, 2, 3, 5, 6, 4)
(1, 0, 2, 3, 6, 4, 5)
(1, 0, 2, 3, 6, 5, 4)
(1, 0, 2, 4, 3, 5, 6)
(1, 0, 2, 4, 3, 6, 5)
(1, 0, 2, 4, 5, 3, 6)
(1, 0, 2, 4, 5, 6, 3)
(1, 0, 2, 4, 6, 3, 5)
(1, 0, 2, 4, 6, 5, 3)
(1, 0, 2, 5, 3, 4, 6)
(1, 0, 2, 5, 3, 6, 4)
(1, 0, 2, 5, 4, 3, 6)
(1, 0, 2, 5, 4, 6, 3)
(1, 0, 2, 5, 6, 3, 4)
(1, 0, 2, 5, 6, 4, 3)
(1, 0, 2, 6, 3, 4, 5)
(1, 0, 2, 6, 3, 5, 4)
(1, 0, 2, 6, 4, 3, 5)
(1, 0, 2, 6, 4, 5, 3)
(1, 0, 2, 6, 5, 3, 4)
(1, 0, 2, 6, 5, 4, 3)
(1, 0, 3, 2, 4, 5, 6)
(1, 0, 3, 2, 4, 6, 5)
(1, 0, 3, 2, 5, 4, 6)
(1, 0, 3, 2, 5, 6, 4)
(1, 0, 3, 2, 6, 4, 5)
(1, 0, 3, 2, 6, 5, 4)
(1, 0, 3, 4, 2, 5, 6)
(1, 0, 3, 4, 2, 6, 5)
(1, 0, 3, 4, 5, 2, 6)
(1, 0, 3, 4, 5, 6, 2)
(1, 0, 3, 4, 6, 2, 5)
(1, 0, 3, 4, 6, 5, 2)
(1, 0, 3, 5, 2, 4, 6)
(1, 0, 3, 5, 2, 6, 4)
(1, 0, 3, 5, 4, 2, 6)
(1, 0, 3, 5, 4, 6, 2)
(1, 0, 3, 5, 6, 2, 4)
(1, 0, 3, 5, 6, 4, 2)
(1, 0, 3, 6, 2, 4, 5)
(1, 0, 3, 6, 2, 5, 4)
(1, 0, 3, 6, 4, 2, 5)
(1, 0, 3, 6, 4, 5, 2)
(1, 0, 3, 6, 5, 2, 4)
(1, 0, 3, 6, 5, 4, 2)
(1, 0, 4, 2, 3, 5, 6)
(1, 0, 4, 2, 3, 6, 5)
(1, 0, 4, 2, 5, 3, 6)
(1, 0, 4, 2, 5, 6, 3)
(1, 0, 4, 2, 6, 3, 5)
(1, 0, 4, 2, 6, 5, 3)

In [37]:
df_merged

,Equation,loss,Predicted Equation,equivalent
Filename,,,,
test_8,E_n/(E_n*(1 - cos(theta))/(c**2*m) + 1),2.257574e-02,log(E_n_var**c_var/theta_var + m_var),False
test_12,q*(4*pi*Volt*d*epsilon - d*q*y**3/(-d**2 + y**...,6.395303e+01,y_var*exp(2.7743993/q_var),False
test_3,d*(1 - alpha**2)/(alpha*cos(theta1 - theta2) + 1),1.658714e-01,d_var*(0.8596411 - alpha_var),False
test_4,sqrt(2)*sqrt((E_n - L**2/(2*m*r**2) - U)/m),3.004066e-02,sqrt(E_n_var) + cos(m_var),False
test_13,q/(4*pi*epsilon*sqrt(d**2 - 2*d*r*cos(alpha) +...,1.058070e-04,0.24866651/(alpha_var*(r_var - cos(d_var))),False
test_17,(m**2*omega**2*x**2*(alpha*x/y + 1) + p**2)/(2*m),5.586157e+04,alpha_var*m_var*(omega_var*x_var)**2.303521/y_var,False
test_20,alpha**2*h**2*omega_0**2*(omega/omega_0 - sin(...,1.250604e+02,(h_var/(m_var*omega_var))**omega_0_var,False
test_19,-(H_G**2*c**2*(1 - 2*alpha) + c**4*k_f/r**2)/(...,9.108685e+01,alpha_var*r_var,False
test_9,-32*G**4*m1**2*m2**2*(m1 + m2)/(5*c**5*r**5),3.252557e+06,-941.02527*(m2_var**(0.45194152*G_var/r_var)/c...,False
test_18,3*(H_G**2 + c**2*k_f/r**2)/(8*pi*G),4.355213e-01,0.26880643*r_var,False
test_2,k_G*m*(sqrt(2*E_n*L**2/(k_G**2*m) + 1)*cos(the...,3.945478e-01,k_G_var*m_var*(cos(theta1_var - theta2_var) + ...,False
test_15,omega*sqrt(1 - v**2/c**2)/(1 + v*cos(theta)/c),8.182781e-03,omega_var - omega_var*cos(theta_var)/(c_var/v_...,False
test_6,sqrt(2*E_n*L**2*epsilon**2/(Z_1**2*Z_2**2*m*q*...,6.756554e-02,L_var**(epsilon_var/(Z_1_var*Z_2_var*q_var)),False
test_5,2*pi*d**(3/2)/sqrt(G*(m1 + m2)),2.493879e+00,2.4023688**d_var,False
test_16,Volt*q + sqrt(c**4*m**2 + c**2*(-A_vec*q + p)**2),3.278112e+02,16.337612*c_var,False
test_1,Z_1**2*Z_2**2*alpha**2*c**2*hbar**2/(16*E_n**2...,2.466390e+01,alpha_var*(c_var*hbar_var*exp(Z_2_var)/E_n_var...,False
test_11,4*I_0*sin(alpha/2)**2*sin(delta*n/2)**2/(alpha...,1.210853e-01,sqrt((I_0_var*(cos(alpha_var) + 2.474374)/sqrt...,False
test_7,sqrt(8*pi*G*rho/3 - alpha*c**2/d**2),4.217456e-02,1.3909392*G_var + 1.3909392*rho_var,False
test_10,arccos((cos(theta2) - v/c)/(1 - v*cos(theta2)/c)),1.854568e-03,theta2_var + v_var*sin(theta2_var)/c_var,False
test_14,Ef*(d**3*(alpha - 1)/(r**2*(alpha + 2)) - r)*c...,7.134909e+00,Ef_var*(-r_var + 0.7289834*exp(d_var - r_var)*...,False

In [21]:
df_merged[df_merged['equivalent']==True]

Empty DataFrame
Columns: [Equation, loss, Predicted Equation, equivalent]
Index: []

In [42]:
df_merged.to_csv('llm_guided_results_50_eqs')
# df_merged.to_csv('non_guided_results_20_eqs')
# score (pysr with defaults) = 46/97 (appx 47%) # took at most a minute to run
# score (pysr with added sqrt, sin, exp, cos) = 55/97 (appx 56%) ~ took about 30 minutes to run


# previous run: 9 correct equations predicted out of 20 (ran in 30 minutes) - LLM aided
# current run: 8 correct equations predicted out of 20 (ran in 7 minutes)

In [43]:
df_guided = pd.read_csv('llm_guided_results_50_eqs')
df_unguided = pd.read_csv('llm_unguided_results_50_eqs')
df_guided.set_index('Filename')
df_unguided.set_index('Filename')
x=df_guided.merge(df_unguided,on='Filename')[['Filename','Equation_x','Predicted Equation_x','loss_x', 'Predicted Equation_y','loss_y','equivalent_x','equivalent_y']]

In [44]:
# 0-1  scale the loss: do (x-min)/max-min
loss_guided = x['loss_x']
loss_unguided=x['loss_y']
loss_guided_scaled=(loss_guided-loss_guided.min())/(loss_guided.max()-loss_guided.min())
loss_unguided_scaled=(loss_unguided-loss_unguided.min())/(loss_unguided.max()-loss_unguided.min())
print('avg 0-1 scaled loss for guided: ', loss_guided_scaled.mean()  )
print('avg 0-1 scaled loss for unguided: ', loss_unguided_scaled.mean() )
print(x[(x['equivalent_x'] == True) & (x['equivalent_y'] == False)].shape[0])
print(x[(x['equivalent_x'] == False) & (x['equivalent_y'] == True)].shape[0])

avg 0-1 scaled loss for guided:  0.06709079776512988
avg 0-1 scaled loss for unguided:  0.02031817688980432
3
4