In [3]:
#import pysr
import pandas as pd
import os
from pysr import PySRRegressor,TensorBoardLoggerSpec
import sympy
import numpy as np
import itertools
import random
import ast
import re
import warnings
warnings.filterwarnings("ignore")

Detected IPython. Loading juliacall extension. See https://juliapy.github.io/PythonCall.jl/stable/compat/#IPython

In [4]:
# create dataframes 
dir = "datasets/Feynman/Feynman_with_units"
df_dict={}
mean=0
gamma = 0.01 # changed from 0.001
for file in os.listdir(dir):
    if file in ['I.15.10.txt', 'I.48.20.txt', 'II.11.7.txt']:
        continue # these dont have a corresponding entry in the metadata file for some reason...
    fname = os.fsdecode(file)
    df = pd.read_csv(os.path.join(dir,fname),sep=" ",header=None,engine='pyarrow') # switching engine to pyarrow sped up loading by nearly 6x
    # add noise to the target variable as described by the paper Symbolic Regression with a Learned Concept Library
    std = gamma*np.sqrt((1/df.shape[0])*np.sum((df.iloc[:,-1:])**2))
    noise_array = np.random.normal(mean, std, size=df.shape[0])
    df.iloc[:,-1] = df.iloc[:,-1] + noise_array
    dfname,_ = os.path.splitext(fname)
    df_dict[dfname] = df

print("DFs created")
file="best_equations.csv",  

c=0

DFs created

In [5]:
class ConvertMinus(ast.NodeTransformer):
    def visit_UnaryOp(self,node):
        self.generic_visit(node)
        if isinstance(node.op,ast.USub):
            return ast.BinOp(left=ast.Constant(value=0),op=ast.Sub(),right=node.operand)
    
        return node

In [6]:
from pydantic import BaseModel,Field,field_validator
import typing

class ResponseStructure(BaseModel):
    expressions:typing.List[str] = Field(...,min_length=1,max_length=3,description="A list of expressions generated by the model")
    
    @field_validator("expressions",mode='before')
    @classmethod
    def remove_equals(cls, v):
        if isinstance(v, list):
            cleaned_expressions = []
            for expr in v:
                if isinstance(expr, str) and '=' in expr:
                    clean_expr = expr.split('=', 1)[-1].strip()
                    cleaned_expressions.append(clean_expr)
                else:
                    cleaned_expressions.append(expr)
            return cleaned_expressions
        return v
        
    
    @field_validator("expressions")
    @classmethod
    def check_equations(cls,expr_list):
        clean_list=[]
        for expr in expr_list:
            if '**' in expr:
                raise ValueError("invalid julia syntax for ** in {expr}. Must use ^ ")
            test_expr = expr.replace("^", "**")
            try:
                tree=ast.parse(test_expr,mode='eval')
                tree=ConvertMinus().visit(tree)
                clean_expr = ast.unparse(tree).replace("**", "^")
                clean_list.append(clean_expr)
            except SyntaxError as e:
                raise ValueError(f"Syntax error in expression '{expr}': {e}")
        return clean_list
        
schema = ResponseStructure.model_json_schema()

In [7]:
df_meta = pd.read_csv('datasets/Feynman/FeynmanEquations.csv') # get the number of variables, the variable names 
df_units = pd.read_csv('datasets/Feynman/units.csv')
unit_map = df_units.set_index('Variable')['Units'].to_dict()

In [27]:
import sympy as sp
import matplotlib.pyplot as plt
import numpy as np

def get_complexity(tree):
    # this is just the number of nodes in the equation tree by default
    if not tree.args:
        return 1 
    
    return 1 + sum(get_complexity(subtree) for subtree in tree.args)
   

def get_string_accuracy(eq_string,X,y_true,variables):
    eq_string = eq_string.replace("^", "**")
    sym_vars = sp.symbols(variables)
    local_dict = {var: sp.Symbol(var) for var in variables}
    expr = sp.sympify(eq_string, locals=local_dict)
    expr_complexity = get_complexity(expr)
    eq = sp.lambdify(sym_vars,expr,modules=['numpy'])
    y_pred = eq(*[X[var] for var in variables])
    return (np.mean((y_true - y_pred)**2),expr_complexity)
    

def get_accuracy(equation,X,y_true):
    # equation is the lambda form of an equation
    y_pred = equation(X)
    return np.mean((y_true-y_pred)**2)
    

def get_complexity_accuracy(X, y_true, equations_df, variables, llm_suggestions=None):
    # Assume that the X df is defines columns in the same order as is in FeynmanEquations.csv. 
    # 1000 rows for speed
    mse_pysr = list(equations_df['lambda_format'].apply(lambda eq : get_accuracy(eq,X,y_true)) )
    complexity_pysr = list(equations_df['complexity'])
    mse_complexity_llm = []
    if llm_suggestions:        
        for llm_eq in llm_suggestions:
            try:
                mse_complexity_llm.append(get_string_accuracy(llm_eq,X,y_true,variables))      
            except Exception:
                pass
                
    return list(zip(mse_pysr,complexity_pysr)),mse_complexity_llm


import matplotlib.pyplot as plt
import numpy as np
import os

def plot_complexity_accuracy(name, data, guided):
    prefix = "guided" if guided else "unguided"
    save_dir = f'complexity_accuracy_plots_{prefix}/{name}'    
    os.makedirs(save_dir, exist_ok=True)
    
    plt.figure(figsize=(10, 6))
    cmap = plt.get_cmap('nipy_spectral')
    colors = [cmap(i) for i in np.linspace(0, 0.95, 30)] 
    
    for idx, (key, val) in enumerate(data.items()):
        # Unpack the new data structure
        arr, pysr_rate, llm_rate = val
        pysr_data, llm_data = arr
        
        color = colors[idx % len(colors)] 
        
        pysr_mse = [mse for mse, comp in pysr_data]
        pysr_comp = [comp for mse, comp in pysr_data]
        
        # Format the label to include the PySR fake variable percentage
        pysr_label = f'{key} PySR [{pysr_rate:.0%} fake]'
        plt.scatter(pysr_comp, pysr_mse, color=color, alpha=0.3, label=pysr_label)
        
        # If LLM data exists, plot it with its specific fake rate
        if llm_data and llm_rate is not None:
            llm_mse = [mse for mse, comp in llm_data]
            llm_comp = [comp for mse, comp in llm_data]
            llm_label = f'{key} LLM [{llm_rate:.0%} fake]'
            
            plt.scatter(llm_comp, llm_mse, color=color, marker='x', s=100, linewidths=2, label=llm_label)
            
    # Removed the global fake_rate from the title since it's now per-iteration
    plt.title(f'Complexity vs. MSE Evolution ({name})\nTracking Dummy Variable Infection')
    plt.xlabel('Complexity (Number of Nodes)')
    plt.ylabel('Mean Squared Error (MSE)')
    plt.yscale('log')
    
    # Adjust legend so it fits well with the longer labels
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', fontsize='small')
    plt.grid(True, which="both", ls="--", alpha=0.5)
    
    save_path = os.path.join(save_dir, 'complexity-accuracy-plots.png')
    plt.savefig(save_path, bbox_inches='tight')
    plt.close()

In [ ]:
import openai
from typing import List,Tuple,Any
import json
import pandas as pd
import re

def call_model(schema:dict[str,Any],
              equations:pd.DataFrame,
              meta:pd.DataFrame,
              df_name:str,
              safe_vars:List[str],
              current_units:dict,
              target_variable:str,
              target_unit:str,
              MAX_ATTEMPTS:int=20,
              MAX_REQ_EXPRS:int=3,
              error_info=None) -> List[Any]:   

    client = openai.OpenAI(
        base_url="https://eleanora-unaggravating-ochlocratically.ngrok-free.dev/v1", 
        api_key = "sk-no-key-required"
    )
    parsed=None
    out='{}'
    
    allowed_vars_regex = "|".join(re.escape(v) for v in safe_vars)
    regex_string = rf"^([0-9+*/^() .-]|{allowed_vars_regex}|sin|cos|exp|log|sqrt)+$"
    schema["properties"]["expressions"]["items"]["pattern"] = regex_string
    correct_expr_list=[]
    wrong_expr_list=[]
    attempts=0
    
    while len(correct_expr_list) < MAX_REQ_EXPRS: # either get 3 correct equations or no
        if attempts == MAX_ATTEMPTS:
            break  

        completion = client.chat.completions.create(
            model="local-model",
            messages=[
                {
                    "role": "system",
                    "content": f"""You are an expert physicist and an AI assistant designed to guide a symbolic regression algorithm. 
                                CRITICAL CONSTRAINTS:
                                1. Output MUST be a valid JSON object strictly following this schema: {json.dumps(schema)}
                                2. Rely ONLY on known, established physical laws. Do not invent new physics.
                                """
                },
                {
                    "role": "user",
                    "content": f'''
                                {error_info if error_info is not None else ""}
                                
                                Your task is to generate THREE candidate mathematical expressions for the target physical quantity.
                                
                                TARGET QUANTITY: {target_variable}
                                TARGET UNIT: {target_unit}
                                
                                ADVERSARIAL WARNING: 
                                To test the robustness of the regression, I have intentionally injected completely irrelevant "dummy" variables into the available variables list. 
                                You must use your knowledge of standard physics to identify the TRUE formula for the target variable and IGNORE the dummy variables. 
                                
                                AVAILABLE VARIABLES: {safe_vars}
                                VARIABLE UNITS: {current_units}
                                
                                STRICT REQUIREMENTS:
                                1. Expressions MUST be valid Julia syntax.
                                2. You must ONLY use the most physically relevant variables from the list.
                                3. Ensure dimensional consistency (the right side of the equation must evaluate to {target_unit}).
                                4. Use the EXACT variable names provided.
                                '''
                } 
            ],
            response_format={
                "type": "json_object",
                "schema": schema
            },
            temperature=0.1, # Lowered temperature for stricter factual recall
        )

# give it two equations from pareto front and evaulate the score and make it give three new equations.
# evaluate new baseline: 1+1 EA. ... 
# TODO: Try to not  add the hall of fame        
#TODO: in the final report, say something about whether or not the output was used, 
# TODO: how often it was syntactically correct, whether or not it copid the call of fame.
# take population, take two individuals from population (two ways: first way: piuck 2 indiviudals and ask LLM to pick one. as opposed to randomly picking two individuals) 
# use other bselines... (risk is there that it does not work. ) 
# Check if it works on a harder dataset. 
# take equations, MSE, send it back to it and reprompt until mse threshold is reached. 

        try:
            out=completion.choices[0].message.content
            
            print(f"validating {out} ... ")
            parsed = ResponseStructure.model_validate_json(out)
            print("validated successfully")           
            
            for eq in parsed.expressions:
                if eq not in correct_expr_list:
                    correct_expr_list.append(eq)              
        except Exception as e:
            wrong_expr_list.append(out)       
            print(f"Validation failed with {e}. Retrying. Attempt# {attempts+1}")
            
        attempts+=1
    
    print("final expression list: ")
    print(correct_expr_list)
    return correct_expr_list

In [28]:
UNARY_OPERATORS=["sqrt","exp","sin","cos","log"]
BINARY_OPERATORS=["+", "*", "/", "^","-"]

def get_variables(list_str): # returns variables in a list of strings
    return set([node.id for formula in list_str for node in ast.walk(ast.parse(formula.replace('^', '**'), mode='eval'))
                                if isinstance(node, ast.Name) and node.id not in set(UNARY_OPERATORS)
                                ])
    
    
    

def run_search(df_dict,fresh_start=False,guided=False):
    MAX_CALLS=19
    MAX_FITTING_ERRORS=5

    c=0
    best_list=[]
    if fresh_start is False:
        # read the file where we have stopped. 
        if os.path.exists('current_run.txt'):
            with open ('current_run.txt','r') as f:
                already_read=set(f.read().splitlines())
            all_dfs = set(df_dict.keys())
            to_read=all_dfs-already_read
            # re-create df_dict so next code can be reused
            df_dict={fname:df_dict[fname] for fname in to_read}  
         
        else:                        
            print("current_run.txt does not exist. Reverting to fresh start.")
    else:
        if os.path.exists('current_run.txt'):
            # remove it
            os.remove('current_run.txt')
        if guided and os.path.exists('best_eqs_20_guided.csv'):
                os.remove('best_eqs_20_guided.csv')
           
        elif not guided and os.path.exists('best_eqs_20_unguided.csv'):
                os.remove('best_eqs_20_unguided.csv')

    for name,df in df_dict.items():
        if c==20:
            break
        num_vars = int(df_meta.loc[df_meta['Filename'] == name, '# variables'].values[0])
        raw_vars = [df_meta.loc[df_meta['Filename'] == name, f'v{i+1}_name'].values[0] for i in range(num_vars)]
        variables = [f"{v}_var" for v in raw_vars]
        target_variable = df_meta.loc[df_meta['Filename']==name, 'Output'].values[0]
        print("Target variable: ",target_variable)
        current_units = {raw: unit_map.get(raw) for raw in raw_vars}
        target_unit = unit_map.get(target_variable)
        print("Target unit: ",target_unit)
        y = df.iloc[:10000, -1].values 
        X = df.iloc[:10000, -(num_vars + 1):-1].copy()
        # hoping and praying that order is kept the same in the metadata file and in the dataset
        X.columns = variables
        # Adding dummy variables for stress testing ....
        all_distractors = {'temperature_var':'K', 'magnetic_flux_var':'Wb', 'luminosity_var':'cd', 'pressure_var':'Pa', 'entropy_var':'J/K'}
        # TODO: add columns that are a random combination of other columns to throw pysr off. The LLM will hopefully ignore the irrelevant variables. 
        
        three = random.sample(list(all_distractors.items()),3) # list of tuples 
        num = len(X.columns)
        # get num number of random ints in the range 0 - 10, so we can do a weighted sum.     
        for var,unit in three:
            X[var] = sum(X.iloc[:,i].values*val for i,val in enumerate(random.sample(range(10),num)))
            variables.append(var)
            current_units[var]=unit
        num_vars=len(variables)
        print(f"Bloated X shape to {X.shape}. Variables are now: {variables}")
        print(f"Going through DF {c+1} solving for equation {name}, X shape: {X.shape}, y shape: {y.shape}")
        logger_spec = TensorBoardLoggerSpec(
                        log_dir="logs/run",
                        log_interval=5,  # Log every 5 iterations
                        )   
        #trying to  restrict pysr..
        model=PySRRegressor(niterations=5, 
                            warm_start=True,
                            guesses=[],
                            populations=5,
                            population_size=20,
                            tournament_selection_n=2,
                            batching=True,
                            batch_size=32,
                            verbosity=0,
                            early_stop_condition= 1e-3, # 0.001 loss. 
                            constraints={"sin": 10, "cos": 10,
                                        "exp": 20, "log": 20, "sqrt": 20,
                                        "pow": (-1, 20)},
                            nested_constraints={"sin": {"sin": 0, "cos": 0},
                                                "cos": {"sin": 0, "cos": 0},
                                                "exp": {"exp":0, "log": 0},
                                                "log": {"exp": 0, "log": 0},
                                                "sqrt": {"sqrt": 0}},
                            unary_operators=UNARY_OPERATORS,
                            binary_operators=BINARY_OPERATORS,
                            fraction_replaced_guesses=0.01, # default is 0.001
                            logger_spec=logger_spec) # constraints taken from paper. 

        model.fit(X,y)
        distractor_set = set([var for var, _ in three])
        data={}
        pysr_vars = get_variables(model.equations_['sympy_format'].astype(str).tolist())
        pysr_fake_rate = len(distractor_set.intersection(pysr_vars)) / len(pysr_vars) if pysr_vars else 0.0
        arr = get_complexity_accuracy(X, y, model.equations_, variables)
        data['Initial Baseline'] = (arr, pysr_fake_rate, None)
        for iter in range (MAX_CALLS):

            if guided and random.random()<0.1: # 10% of the time
                fitting_errors=0
                print(f"LLM called. Sending equations and meta info")
                

                llm_guesses = call_model(schema,model.equations_,df_meta,name,variables,current_units,target_variable,target_unit)
                model.set_params(guesses=llm_guesses)
                while fitting_errors<MAX_FITTING_ERRORS:                    
                    try:   
                        model.fit(X,y) # runs for 5 iterations
                        pysr_vars = get_variables(model.equations_['sympy_format'].astype(str).tolist())
                        # for logging purposes, get the number of dummy variables injected and store it. 
                        llm_response_vars = get_variables(llm_guesses)
                        pysr_fake_rate = len(distractor_set.intersection(pysr_vars)) / len(pysr_vars) if pysr_vars else 0.0
                        llm_fake_rate = len(distractor_set.intersection(llm_response_vars)) / len(llm_response_vars) if llm_response_vars else 0.0
                        
                        # after successful fit, add these to the plot. 
                        arr = get_complexity_accuracy(X, y, model.equations_, variables, llm_guesses) 
                        data[f'Iter {iter+1}'] = (arr, pysr_fake_rate, llm_fake_rate)                            
                        break
                    except Exception as e: # try again
                        fitting_errors+=1
                        e=str(e)
                        print(f"Exception {e} encountered when fitting. Trying again. (Attempt: {fitting_errors})")
                        if 'Stacktrace' in e:
                            message,_ = e.split('Stacktrace:',1)    
                        else:
                            message=e   
                        message += f' The error is here: {llm_guesses}. Please re-generate the guesses after correction'   
                
                        llm_guesses = call_model(schema,model.equations_,df_meta,name,variables,current_units,target_variable,target_unit,error_info=message)
                        model.set_params(guesses=llm_guesses)

                # reset for the next iteration. 
                model.set_params(guesses=[])
            else:
                # continue as normal 
                model.fit(X,y)
                pysr_vars = get_variables(model.equations_['sympy_format'].astype(str).tolist())
                pysr_fake_rate = len(distractor_set.intersection(pysr_vars)) / len(pysr_vars) if pysr_vars else 0.0
                arr = get_complexity_accuracy(X, y, model.equations_, variables)
                data[f'Iter {iter+1}'] = (arr, pysr_fake_rate, None)
        # plot this
        if data: 
            plot_complexity_accuracy(name, data, guided)
        

        best=model.equations_.sort_values("score",axis=0,ascending=False).iloc[[0]].copy() # score chooses the equation with the best complexity-accuracy trade off.
        best["Filename"] = name 
        
        if guided:
            best.to_csv('best_eqs_20_guided.csv', mode='a', index=False, header=not os.path.exists('best_eqs_20_guided.csv'))
        else:
            best.to_csv('best_eqs_20_unguided.csv', mode='a', index=False, header=not os.path.exists('best_eqs_20_unguided.csv'))

            
        best_list.append(best)
        # save the name of the df into a text file 
        with open ('current_run.txt','a') as f:
            f.write(f'{name}\n')
        c+=1

In [32]:
run_search(df_dict,fresh_start=True,guided=False)

Target variable:  k
Target unit:  Wave number
Bloated X shape to (10000, 6). Variables are now: ['alpha_var', 'n_var', 'd_var', 'temperature_var', 'luminosity_var', 'pressure_var']
Going through DF 1 solving for equation III.15.27, X shape: (10000, 6), y shape: (10000,)
Target variable:  E_n
Target unit:  Energy
Bloated X shape to (10000, 7). Variables are now: ['h_var', 'omega_var', 'kb_var', 'T_var', 'pressure_var', 'temperature_var', 'entropy_var']
Going through DF 2 solving for equation III.4.33, X shape: (10000, 7), y shape: (10000,)
Target variable:  E_n
Target unit:  Energy
Bloated X shape to (10000, 7). Variables are now: ['m_var', 'omega_var', 'omega_0_var', 'x_var', 'temperature_var', 'magnetic_flux_var', 'luminosity_var']
Going through DF 3 solving for equation I.24.6, X shape: (10000, 7), y shape: (10000,)
Target variable:  prob
Target unit:  Dimensionless
Bloated X shape to (10000, 9). Variables are now: ['p_d_var', 'Ef_var', 't_var', 'h_var', 'omega_var', 'omega_0_var', 'temperature_var', 'luminosity_var', 'entropy_var']
Going through DF 4 solving for equation III.9.52, X shape: (10000, 9), y shape: (10000,)
Target variable:  omega
Target unit:  Frequency
Bloated X shape to (10000, 6). Variables are now: ['c_var', 'v_var', 'omega_0_var', 'temperature_var', 'magnetic_flux_var', 'luminosity_var']
Going through DF 5 solving for equation I.34.14, X shape: (10000, 6), y shape: (10000,)
Target variable:  omega
Target unit:  Frequency
Bloated X shape to (10000, 6). Variables are now: ['mom_var', 'B_var', 'h_var', 'luminosity_var', 'pressure_var', 'temperature_var']
Going through DF 6 solving for equation III.7.38, X shape: (10000, 6), y shape: (10000,)
Target variable:  E_n
Target unit:  Energy
Bloated X shape to (10000, 6). Variables are now: ['mom_var', 'B_var', 'theta_var', 'entropy_var', 'magnetic_flux_var', 'luminosity_var']
Going through DF 7 solving for equation II.15.4, X shape: (10000, 6), y shape: (10000,)
Target variable:  L_rad
Target unit:  Spectral radiance
Bloated X shape to (10000, 8). Variables are now: ['omega_var', 'T_var', 'h_var', 'kb_var', 'c_var', 'entropy_var', 'pressure_var', 'magnetic_flux_var']
Going through DF 8 solving for equation I.41.16, X shape: (10000, 8), y shape: (10000,)
Target variable:  tau
Target unit:  Torque
Bloated X shape to (10000, 5). Variables are now: ['r_var', 'F_var', 'pressure_var', 'entropy_var', 'temperature_var']
Going through DF 9 solving for equation I.18.12, X shape: (10000, 5), y shape: (10000,)
Target variable:  x
Target unit:  Length
Bloated X shape to (10000, 8). Variables are now: ['q_var', 'Ef_var', 'm_var', 'omega_0_var', 'omega_var', 'temperature_var', 'luminosity_var', 'magnetic_flux_var']
Going through DF 10 solving for equation II.11.3, X shape: (10000, 8), y shape: (10000,)
Target variable:  Volt
Target unit:  Voltage
Bloated X shape to (10000, 8). Variables are now: ['q_var', 'epsilon_var', 'r_var', 'v_var', 'c_var', 'temperature_var', 'pressure_var', 'magnetic_flux_var']
Going through DF 11 solving for equation II.21.32, X shape: (10000, 8), y shape: (10000,)
Target variable:  Ef
Target unit:  Electric field
Bloated X shape to (10000, 7). Variables are now: ['epsilon_var', 'p_d_var', 'theta_var', 'r_var', 'luminosity_var', 'magnetic_flux_var', 'pressure_var']
Going through DF 12 solving for equation II.6.15b, X shape: (10000, 7), y shape: (10000,)
Target variable:  E_n
Target unit:  Energy
Bloated X shape to (10000, 8). Variables are now: ['g__var', 'h_var', 'Jz_var', 'mom_var', 'B_var', 'entropy_var', 'temperature_var', 'pressure_var']
Going through DF 13 solving for equation II.34.29b, X shape: (10000, 8), y shape: (10000,)
Target variable:  U
Target unit:  Energy
Bloated X shape to (10000, 6). Variables are now: ['m_var', 'g_var', 'z_var', 'luminosity_var', 'temperature_var', 'entropy_var']
Going through DF 14 solving for equation I.14.3, X shape: (10000, 6), y shape: (10000,)
Target variable:  U
Target unit:  Energy
Bloated X shape to (10000, 8). Variables are now: ['m1_var', 'm2_var', 'r1_var', 'r2_var', 'G_var', 'pressure_var', 'entropy_var', 'magnetic_flux_var']
Going through DF 15 solving for equation I.13.12, X shape: (10000, 8), y shape: (10000,)
Target variable:  m
Target unit:  Mass
Bloated X shape to (10000, 6). Variables are now: ['m_0_var', 'v_var', 'c_var', 'luminosity_var', 'temperature_var', 'entropy_var']
Going through DF 16 solving for equation I.10.7, X shape: (10000, 6), y shape: (10000,)
Target variable:  F
Target unit:  Force
Bloated X shape to (10000, 5). Variables are now: ['q2_var', 'Ef_var', 'pressure_var', 'temperature_var', 'luminosity_var']
Going through DF 17 solving for equation I.12.5, X shape: (10000, 5), y shape: (10000,)
Target variable:  v
Target unit:  Velocity
Bloated X shape to (10000, 7). Variables are now: ['mu_drift_var', 'q_var', 'Volt_var', 'd_var', 'temperature_var', 'luminosity_var', 'entropy_var']
Going through DF 18 solving for equation I.43.16, X shape: (10000, 7), y shape: (10000,)
Target variable:  E_n
Target unit:  Energy
Bloated X shape to (10000, 6). Variables are now: ['p_d_var', 'Ef_var', 'theta_var', 'entropy_var', 'luminosity_var', 'temperature_var']
Going through DF 19 solving for equation II.15.5, X shape: (10000, 6), y shape: (10000,)
Target variable:  F
Target unit:  Force
Bloated X shape to (10000, 8). Variables are now: ['q_var', 'Ef_var', 'B_var', 'v_var', 'theta_var', 'entropy_var', 'luminosity_var', 'pressure_var']
Going through DF 20 solving for equation I.12.11, X shape: (10000, 8), y shape: (10000,)

In [31]:
run_search(df_dict,fresh_start=True,guided=True)

Target variable:  k
Target unit:  Wave number
Bloated X shape to (10000, 6). Variables are now: ['alpha_var', 'n_var', 'd_var', 'pressure_var', 'luminosity_var', 'temperature_var']
Going through DF 1 solving for equation III.15.27, X shape: (10000, 6), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["1 / d_var", "n_var * 2 * pressure_var / (luminosity_var * temperature_var)", "sqrt(n_var)"]} ...
validated successfully
final expression list:
['1 / d_var', 'n_var * 2 * pressure_var / (luminosity_var * temperature_var)', 'sqrt(n_var)']
Target variable:  E_n
Target unit:  Energy
Bloated X shape to (10000, 7). Variables are now: ['h_var', 'omega_var', 'kb_var', 'T_var', 'luminosity_var', 'pressure_var', 'magnetic_flux_var']
Going through DF 2 solving for equation III.4.33, X shape: (10000, 7), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["kb_var * T_var", "luminosity_var / pressure_var", "magnetic_flux_var * omega_var"]} ...
validated successfully
final expression list:
['kb_var * T_var', 'luminosity_var / pressure_var', 'magnetic_flux_var * omega_var']
LLM called. Sending equations and meta info
validating {"expressions": ["kb_var * T_var", "luminosity_var / pressure_var", "magnetic_flux_var * omega_var"]} ...
validated successfully
final expression list:
['kb_var * T_var', 'luminosity_var / pressure_var', 'magnetic_flux_var * omega_var']
LLM called. Sending equations and meta info
validating {"expressions": ["kb_var * T_var", "luminosity_var / pressure_var", "magnetic_flux_var * omega_var"]} ...
validated successfully
final expression list:
['kb_var * T_var', 'luminosity_var / pressure_var', 'magnetic_flux_var * omega_var']
LLM called. Sending equations and meta info
validating {"expressions": ["kb_var * T_var", "luminosity_var / pressure_var", "magnetic_flux_var * omega_var"]} ...
validated successfully
final expression list:
['kb_var * T_var', 'luminosity_var / pressure_var', 'magnetic_flux_var * omega_var']
Target variable:  E_n
Target unit:  Energy
Bloated X shape to (10000, 7). Variables are now: ['m_var', 'omega_var', 'omega_0_var', 'x_var', 'pressure_var', 'magnetic_flux_var', 'luminosity_var']
Going through DF 3 solving for equation I.24.6, X shape: (10000, 7), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["m_var * omega_0_var^2 / 2", "luminosity_var * x_var", "pressure_var * magnetic_flux_var"]} ...
validated successfully
final expression list:
['m_var * omega_0_var ^ 2 / 2', 'luminosity_var * x_var', 'pressure_var * magnetic_flux_var']
LLM called. Sending equations and meta info
validating {"expressions": ["m_var * omega_0_var^2 / 2", "luminosity_var * x_var", "pressure_var * magnetic_flux_var"]} ...
validated successfully
final expression list:
['m_var * omega_0_var ^ 2 / 2', 'luminosity_var * x_var', 'pressure_var * magnetic_flux_var']
LLM called. Sending equations and meta info
validating {"expressions": ["m_var * omega_0_var^2 / 2", "luminosity_var * x_var", "pressure_var * magnetic_flux_var"]} ...
validated successfully
final expression list:
['m_var * omega_0_var ^ 2 / 2', 'luminosity_var * x_var', 'pressure_var * magnetic_flux_var']
Target variable:  prob
Target unit:  Dimensionless
Bloated X shape to (10000, 9). Variables are now: ['p_d_var', 'Ef_var', 't_var', 'h_var', 'omega_var', 'omega_0_var', 'luminosity_var', 'temperature_var', 'pressure_var']
Going through DF 4 solving for equation III.9.52, X shape: (10000, 9), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["p_d_var / Ef_var", "sin(omega_var * t_var)", "exp(-luminosity_var * temperature_var)"]} ...
validated successfully
final expression list:
['p_d_var / Ef_var', 'sin(omega_var * t_var)', 'exp((0 - luminosity_var) * temperature_var)']
LLM called. Sending equations and meta info
validating {"expressions": ["p_d_var / Ef_var", "sin(omega_var * t_var)", "exp(-luminosity_var * temperature_var)"]} ...
validated successfully
final expression list:
['p_d_var / Ef_var', 'sin(omega_var * t_var)', 'exp((0 - luminosity_var) * temperature_var)']
LLM called. Sending equations and meta info
validating {"expressions": ["p_d_var / Ef_var", "sin(omega_var * t_var)", "exp(-luminosity_var * temperature_var)"]} ...
validated successfully
final expression list:
['p_d_var / Ef_var', 'sin(omega_var * t_var)', 'exp((0 - luminosity_var) * temperature_var)']
Target variable:  omega
Target unit:  Frequency
Bloated X shape to (10000, 6). Variables are now: ['c_var', 'v_var', 'omega_0_var', 'magnetic_flux_var', 'pressure_var', 'luminosity_var']
Going through DF 5 solving for equation I.34.14, X shape: (10000, 6), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["omega_0_var", "sin(omega_0_var * v_var)", "sqrt(magnetic_flux_var / pressure_var)"]} ...
validated successfully
final expression list:
['omega_0_var', 'sin(omega_0_var * v_var)', 'sqrt(magnetic_flux_var / pressure_var)']
LLM called. Sending equations and meta info
validating {"expressions": ["omega_0_var", "sin(omega_0_var * v_var / c_var)", "sqrt(magnetic_flux_var / (2 * pressure_var))"]} ...
validated successfully
final expression list:
['omega_0_var', 'sin(omega_0_var * v_var / c_var)', 'sqrt(magnetic_flux_var / (2 * pressure_var))']
LLM called. Sending equations and meta info
validating {"expressions": ["omega_0_var", "sin(omega_0_var * v_var)", "sqrt(magnetic_flux_var / pressure_var)"]} ...
validated successfully
final expression list:
['omega_0_var', 'sin(omega_0_var * v_var)', 'sqrt(magnetic_flux_var / pressure_var)']
Target variable:  omega
Target unit:  Frequency
Bloated X shape to (10000, 6). Variables are now: ['mom_var', 'B_var', 'h_var', 'temperature_var', 'pressure_var', 'entropy_var']
Going through DF 6 solving for equation III.7.38, X shape: (10000, 6), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["sqrt(h_var / (2 * mom_var))", "B_var * temperature_var / pressure_var", "exp(entropy_var / h_var)"]} ...
validated successfully
final expression list:
['sqrt(h_var / (2 * mom_var))', 'B_var * temperature_var / pressure_var', 'exp(entropy_var / h_var)']
LLM called. Sending equations and meta info
validating {"expressions": ["sqrt(h_var / (2 * mom_var))", "B_var * temperature_var / pressure_var", "exp(entropy_var / temperature_var)"]} ...
validated successfully
final expression list:
['sqrt(h_var / (2 * mom_var))', 'B_var * temperature_var / pressure_var', 'exp(entropy_var / temperature_var)']
Target variable:  E_n
Target unit:  Energy
Bloated X shape to (10000, 6). Variables are now: ['mom_var', 'B_var', 'theta_var', 'entropy_var', 'magnetic_flux_var', 'pressure_var']
Going through DF 7 solving for equation II.15.4, X shape: (10000, 6), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["magnetic_flux_var * B_var", "pressure_var * entropy_var", "mom_var * theta_var"]} ...
validated successfully
final expression list:
['magnetic_flux_var * B_var', 'pressure_var * entropy_var', 'mom_var * theta_var']
LLM called. Sending equations and meta info
validating {"expressions": ["magnetic_flux_var * B_var", "pressure_var * entropy_var", "mom_var * theta_var"]} ...
validated successfully
final expression list:
['magnetic_flux_var * B_var', 'pressure_var * entropy_var', 'mom_var * theta_var']
Target variable:  L_rad
Target unit:  Spectral radiance
Bloated X shape to (10000, 8). Variables are now: ['omega_var', 'T_var', 'h_var', 'kb_var', 'c_var', 'luminosity_var', 'magnetic_flux_var', 'pressure_var']
Going through DF 8 solving for equation I.41.16, X shape: (10000, 8), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["luminosity_var / (4 * kb_var * T_var^4)", "h_var * c_var / (kb_var * T_var^3)", "magnetic_flux_var * omega_var / (2 * pressure_var)"]} ...
validated successfully
final expression list:
['luminosity_var / (4 * kb_var * T_var ^ 4)', 'h_var * c_var / (kb_var * T_var ^ 3)', 'magnetic_flux_var * omega_var / (2 * pressure_var)']
Target variable:  tau
Target unit:  Torque
Bloated X shape to (10000, 5). Variables are now: ['r_var', 'F_var', 'magnetic_flux_var', 'luminosity_var', 'temperature_var']
Going through DF 9 solving for equation I.18.12, X shape: (10000, 5), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["F_var * r_var", "magnetic_flux_var * temperature_var", "luminosity_var / (r_var^2)"]} ...
validated successfully
final expression list:
['F_var * r_var', 'magnetic_flux_var * temperature_var', 'luminosity_var / r_var ^ 2']
Target variable:  x
Target unit:  Length
Bloated X shape to (10000, 8). Variables are now: ['q_var', 'Ef_var', 'm_var', 'omega_0_var', 'omega_var', 'luminosity_var', 'temperature_var', 'pressure_var']
Going through DF 10 solving for equation II.11.3, X shape: (10000, 8), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["sqrt(luminosity_var / (4 * Ef_var))", "q_var / omega_0_var", "m_var * omega_var^2"]} ...
validated successfully
final expression list:
['sqrt(luminosity_var / (4 * Ef_var))', 'q_var / omega_0_var', 'm_var * omega_var ^ 2']
Target variable:  Volt
Target unit:  Voltage
Bloated X shape to (10000, 8). Variables are now: ['q_var', 'epsilon_var', 'r_var', 'v_var', 'c_var', 'magnetic_flux_var', 'temperature_var', 'entropy_var']
Going through DF 11 solving for equation II.21.32, X shape: (10000, 8), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["v_var", "magnetic_flux_var / r_var", "epsilon_var * v_var^2"]} ...
validated successfully
final expression list:
['v_var', 'magnetic_flux_var / r_var', 'epsilon_var * v_var ^ 2']
LLM called. Sending equations and meta info
validating {"expressions": ["q_var / epsilon_var", "magnetic_flux_var / r_var", "v_var * c_var"]} ...
validated successfully
final expression list:
['q_var / epsilon_var', 'magnetic_flux_var / r_var', 'v_var * c_var']
LLM called. Sending equations and meta info
validating {"expressions": ["epsilon_var * v_var", "magnetic_flux_var / r_var", "c_var * temperature_var"]} ...
validated successfully
final expression list:
['epsilon_var * v_var', 'magnetic_flux_var / r_var', 'c_var * temperature_var']
LLM called. Sending equations and meta info
validating {"expressions": ["q_var / epsilon_var", "magnetic_flux_var / r_var", "v_var * c_var"]} ...
validated successfully
final expression list:
['q_var / epsilon_var', 'magnetic_flux_var / r_var', 'v_var * c_var']
Target variable:  Ef
Target unit:  Electric field
Bloated X shape to (10000, 7). Variables are now: ['epsilon_var', 'p_d_var', 'theta_var', 'r_var', 'entropy_var', 'luminosity_var', 'magnetic_flux_var']
Going through DF 12 solving for equation II.6.15b, X shape: (10000, 7), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["epsilon_var * p_d_var / r_var^2", "magnetic_flux_var / (2 * r_var)", "p_d_var * sin(theta_var) / r_var"]} ...
validated successfully
final expression list:
['epsilon_var * p_d_var / r_var ^ 2', 'magnetic_flux_var / (2 * r_var)', 'p_d_var * sin(theta_var) / r_var']
LLM called. Sending equations and meta info
validating {"expressions": ["p_d_var / (4 * epsilon_var * r_var^2)", "magnetic_flux_var / (2 * r_var^2)", "epsilon_var * p_d_var * cos(theta_var) / r_var^3"]} ...
validated successfully
final expression list:
['p_d_var / (4 * epsilon_var * r_var ^ 2)', 'magnetic_flux_var / (2 * r_var ^ 2)', 'epsilon_var * p_d_var * cos(theta_var) / r_var ^ 3']
LLM called. Sending equations and meta info
validating {"expressions": ["p_d_var / (4 * epsilon_var * r_var^2)", "magnetic_flux_var / (2 * r_var^2)", "epsilon_var * p_d_var * cos(theta_var) / r_var"]} ...
validated successfully
final expression list:
['p_d_var / (4 * epsilon_var * r_var ^ 2)', 'magnetic_flux_var / (2 * r_var ^ 2)', 'epsilon_var * p_d_var * cos(theta_var) / r_var']
LLM called. Sending equations and meta info
validating {"expressions": ["p_d_var / (4 * epsilon_var * r_var^2)", "magnetic_flux_var / (2 * r_var^2)", "epsilon_var * p_d_var * cos(theta_var) / r_var"]} ...
validated successfully
final expression list:
['p_d_var / (4 * epsilon_var * r_var ^ 2)', 'magnetic_flux_var / (2 * r_var ^ 2)', 'epsilon_var * p_d_var * cos(theta_var) / r_var']
LLM called. Sending equations and meta info
validating {"expressions": ["epsilon_var * p_d_var / r_var^2", "magnetic_flux_var / (2 * r_var)", "p_d_var * sin(theta_var) / r_var"]} ...
validated successfully
final expression list:
['epsilon_var * p_d_var / r_var ^ 2', 'magnetic_flux_var / (2 * r_var)', 'p_d_var * sin(theta_var) / r_var']
Target variable:  E_n
Target unit:  Energy
Bloated X shape to (10000, 8). Variables are now: ['g__var', 'h_var', 'Jz_var', 'mom_var', 'B_var', 'magnetic_flux_var', 'luminosity_var', 'pressure_var']
Going through DF 13 solving for equation II.34.29b, X shape: (10000, 8), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["h_var * B_var", "Jz_var^2 / (2 * mom_var)", "luminosity_var * pressure_var"]} ...
validated successfully
final expression list:
['h_var * B_var', 'Jz_var ^ 2 / (2 * mom_var)', 'luminosity_var * pressure_var']
LLM called. Sending equations and meta info
validating {"expressions": ["h_var * B_var", "Jz_var^2 / (2 * mom_var)", "luminosity_var * pressure_var"]} ...
validated successfully
final expression list:
['h_var * B_var', 'Jz_var ^ 2 / (2 * mom_var)', 'luminosity_var * pressure_var']
LLM called. Sending equations and meta info
validating {"expressions": ["h_var * B_var", "Jz_var^2 / (2 * mom_var)", "luminosity_var * pressure_var"]} ...
validated successfully
final expression list:
['h_var * B_var', 'Jz_var ^ 2 / (2 * mom_var)', 'luminosity_var * pressure_var']
Target variable:  U
Target unit:  Energy
Bloated X shape to (10000, 6). Variables are now: ['m_var', 'g_var', 'z_var', 'magnetic_flux_var', 'entropy_var', 'luminosity_var']
Going through DF 14 solving for equation I.14.3, X shape: (10000, 6), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["magnetic_flux_var * entropy_var", "luminosity_var * z_var^2", "g_var * m_var * z_var"]} ...
validated successfully
final expression list:
['magnetic_flux_var * entropy_var', 'luminosity_var * z_var ^ 2', 'g_var * m_var * z_var']
LLM called. Sending equations and meta info
validating {"expressions": ["magnetic_flux_var * entropy_var", "luminosity_var * g_var", "z_var^2 * magnetic_flux_var"]} ...
validated successfully
final expression list:
['magnetic_flux_var * entropy_var', 'luminosity_var * g_var', 'z_var ^ 2 * magnetic_flux_var']
LLM called. Sending equations and meta info
validating {"expressions": ["magnetic_flux_var * entropy_var", "luminosity_var * z_var^2", "g_var * m_var * z_var"]} ...
validated successfully
final expression list:
['magnetic_flux_var * entropy_var', 'luminosity_var * z_var ^ 2', 'g_var * m_var * z_var']
LLM called. Sending equations and meta info
validating {"expressions": ["magnetic_flux_var * entropy_var", "luminosity_var * g_var", "z_var^2 * magnetic_flux_var"]} ...
validated successfully
final expression list:
['magnetic_flux_var * entropy_var', 'luminosity_var * g_var', 'z_var ^ 2 * magnetic_flux_var']
Target variable:  U
Target unit:  Energy
Bloated X shape to (10000, 8). Variables are now: ['m1_var', 'm2_var', 'r1_var', 'r2_var', 'G_var', 'temperature_var', 'luminosity_var', 'pressure_var']
Going through DF 15 solving for equation I.13.12, X shape: (10000, 8), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["G_var * m1_var * m2_var / (r1_var^2 + r2_var^2)", "0.5 * m1_var * temperature_var^2", "luminosity_var * pressure_var"]} ...
validated successfully
final expression list:
['G_var * m1_var * m2_var / (r1_var ^ 2 + r2_var ^ 2)', '0.5 * m1_var * temperature_var ^ 2', 'luminosity_var * pressure_var']
LLM called. Sending equations and meta info
validating {"expressions": ["G_var * m1_var * m2_var / (r1_var^2 + r2_var^2)", "0.5 * G_var * (m1_var^2 / r1_var^2 + m2_var^2 / r2_var^2)", "luminosity_var * pressure_var"]} ...
validated successfully
final expression list:
['G_var * m1_var * m2_var / (r1_var ^ 2 + r2_var ^ 2)', '0.5 * G_var * (m1_var ^ 2 / r1_var ^ 2 + m2_var ^ 2 / r2_var ^ 2)', 'luminosity_var * pressure_var']
LLM called. Sending equations and meta info
validating {"expressions": ["G_var * m1_var * m2_var / (r1_var + r2_var)^2", "0.5 * G_var * m1_var * m2_var * ((1/r1_var) - (1/r2_var))", "luminosity_var * pressure_var"]} ...
validated successfully
final expression list:
['G_var * m1_var * m2_var / (r1_var + r2_var) ^ 2', '0.5 * G_var * m1_var * m2_var * (1 / r1_var - 1 / r2_var)', 'luminosity_var * pressure_var']
Target variable:  m
Target unit:  Mass
Bloated X shape to (10000, 6). Variables are now: ['m_0_var', 'v_var', 'c_var', 'pressure_var', 'luminosity_var', 'magnetic_flux_var']
Going through DF 16 solving for equation I.10.7, X shape: (10000, 6), y shape: (10000,)
Target variable:  F
Target unit:  Force
Bloated X shape to (10000, 5). Variables are now: ['q2_var', 'Ef_var', 'magnetic_flux_var', 'pressure_var', 'temperature_var']
Going through DF 17 solving for equation I.12.5, X shape: (10000, 5), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["magnetic_flux_var * q2_var", "pressure_var / temperature_var", "q2_var * Ef_var"]} ...
validated successfully
final expression list:
['magnetic_flux_var * q2_var', 'pressure_var / temperature_var', 'q2_var * Ef_var']
Target variable:  v
Target unit:  Velocity
Bloated X shape to (10000, 7). Variables are now: ['mu_drift_var', 'q_var', 'Volt_var', 'd_var', 'luminosity_var', 'temperature_var', 'magnetic_flux_var']
Going through DF 18 solving for equation I.43.16, X shape: (10000, 7), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["q_var * Volt_var / d_var", "mu_drift_var * d_var", "magnetic_flux_var / (2 * q_var)"]} ...
validated successfully
final expression list:
['q_var * Volt_var / d_var', 'mu_drift_var * d_var', 'magnetic_flux_var / (2 * q_var)']
LLM called. Sending equations and meta info
validating {"expressions": ["q_var / d_var", "mu_drift_var * d_var", "magnetic_flux_var / (2 * q_var)"]} ...
validated successfully
final expression list:
['q_var / d_var', 'mu_drift_var * d_var', 'magnetic_flux_var / (2 * q_var)']
LLM called. Sending equations and meta info
validating {"expressions": ["q_var * Volt_var / d_var", "mu_drift_var * d_var", "magnetic_flux_var / (2 * q_var)"]} ...
validated successfully
final expression list:
['q_var * Volt_var / d_var', 'mu_drift_var * d_var', 'magnetic_flux_var / (2 * q_var)']
Target variable:  E_n
Target unit:  Energy
Bloated X shape to (10000, 6). Variables are now: ['p_d_var', 'Ef_var', 'theta_var', 'pressure_var', 'temperature_var', 'luminosity_var']
Going through DF 19 solving for equation II.15.5, X shape: (10000, 6), y shape: (10000,)
LLM called. Sending equations and meta info
validating {"expressions": ["p_d_var * Ef_var", "luminosity_var * theta_var", "pressure_var * temperature_var"]} ...
validated successfully
final expression list:
['p_d_var * Ef_var', 'luminosity_var * theta_var', 'pressure_var * temperature_var']
LLM called. Sending equations and meta info
validating {"expressions": ["Ef_var * theta_var", "p_d_var * Ef_var", "luminosity_var / temperature_var"]} ...
validated successfully
final expression list:
['Ef_var * theta_var', 'p_d_var * Ef_var', 'luminosity_var / temperature_var']
LLM called. Sending equations and meta info
validating {"expressions": ["Ef_var^2 * theta_var", "p_d_var * Ef_var * cos(theta_var)", "luminosity_var * temperature_var"]} ...
validated successfully
final expression list:
['Ef_var ^ 2 * theta_var', 'p_d_var * Ef_var * cos(theta_var)', 'luminosity_var * temperature_var']

In [33]:
symbols = sympy.symbols("""
sigma theta1 x1 x2 y1 y2 m1 m2 G z1
z2 m_0 v c x3 y3 mu Nn q1 q2
epsilon r Ef q B m u w r1 r2
z k_spring x t F omega omega_0 n theta2 d1
d2 Int_0 lambd d a p h I1 I2 delta
pr gamma kb n_0 mu_drift Volt mob V1 V2 rho
alpha kappa T1 T2 Pwr p_d y sigma_den chi n_rho
I rho_c_0 mom g_ Jz E_n Bx By Bz k
I_0 beta A_vec x0 x4 x5 x6 x7 x8 x9
""")
(sigma, theta1, x1, x2, y1, y2, m1, m2, G, z1,
z2, m_0, v, c, x3, y3, mu, Nn, q1, q2,
epsilon, r, Ef, q, B, m, u, w, r1, r2,
z, k_spring, x, t, F, omega, omega_0, n, theta2, d1,
d2, Int_0, lambd, d, a, p, h, I1, I2, delta,
pr, gamma, kb, n_0, mu_drift, Volt, mob, V1, V2, rho,
alpha, kappa, T1, T2, Pwr, p_d, y, sigma_den, chi, n_rho,
I, rho_c_0, mom, g_, Jz, E_n, Bx, By, Bz, k,
I_0, beta, A_vec,x0,x4,x5,x6,x7,x8,x9) = symbols

locals_ = {s.name: s for s in symbols}

In [34]:
# creating the core DF 

df_pred=pd.read_csv("best_eqs_20_unguided.csv")
df_original = pd.read_csv("datasets/Feynman/FeynmanEquations.csv")[["Filename","Formula"]]
df_merged = df_pred.merge(df_original,on="Filename",how='left')
df_merged["Equation"] = df_merged["Formula"].map(lambda f: sympy.sympify(f, locals=locals_))
df_merged["Predicted Equation"] = df_merged["sympy_format"].map(lambda f: sympy.sympify(f, locals=locals_))
df_merged= df_merged[["Filename","Equation","loss","Predicted Equation"]]
df_merged=df_merged.drop_duplicates(subset='Filename').set_index('Filename')
df_merged.drop(df_merged[df_merged['Equation']==sympy.nan].index,inplace=True)

In [35]:
# i want to know how similar these are...
# constants are an issue.. we will try to prove equivalence up to a constant 
pred_eqs = df_merged['Predicted Equation']
orig_eqs = df_merged['Equation']

In [36]:
def check_equality(pred_expr, true_expr, true_varnames=None):
    '''
    used to check if two sympy expressions are "equal".
    equality is defined here as equal upto a constant.
    Works by sampling the true equation and then trying out permutations 
    of the input variables of the candidate solution and obtaining the ratio of the fits. 
    If the ratios are identical, the expressions are equivalent upto a constant.  
    
    '''
    # print("Free symbols in the true expression: ")
    # print(true_expr.free_symbols)
    pred_vars = sorted(pred_expr.free_symbols, key=lambda s: s.name)
    if true_varnames:
        true_vars = [sympy.Symbol(n) for n in true_varnames]
    else:
        true_vars = sorted(true_expr.free_symbols, key=lambda s: s.name)
    # print("variables in the true expression: ")
    print(true_vars)
    if len(pred_vars) != len(true_vars):
        return False
# lambdify
    f_pred = sympy.lambdify(pred_vars, pred_expr, "numpy")
    f_true = sympy.lambdify(true_vars, true_expr, "numpy")
    
# 10 points 
    N_samples = 10
    X = np.random.uniform(1.0, 5.0, (N_samples, len(true_vars)))
    
    # Calculate True Output
    try:
        y_true = f_true(*X.T) # evaluate true function over 10 points. 
    except Exception:
        return False 

    best_perm = None
    
    for perm_indices in itertools.permutations(range(len(true_vars))): # [0,1,2] eg if len is 3
        print(perm_indices) # [0,1,2], [0,2,1]
        try:
            # Reorder columns of X to match this permutation
            X_permuted = X[:, perm_indices]
            
            # Eval prediction
            y_pred = f_pred(*X_permuted.T) # get the fit on y after re-ordering. 
            corr_matrix = np.corrcoef(y_pred, y_true)
            if abs(corr_matrix[0, 1]) > 0.99999:
                best_perm = [true_vars[i] for i in perm_indices]
                break
            
            # Calculate Ratio: y_pred / y_true
            # If equations are equivalent (up to constant), ratio should be identical for all points
            ratio = y_pred / y_true            
            # Check if ratio is constant (sigma is almost 0)
            if np.std(ratio) < 1e-5 and np.isfinite(ratio).all():
                # We found a candidate permutation! 
                # Map the indices back to symbols
                best_perm = [true_vars[i] for i in perm_indices]
                break
                
        except Exception:
            continue

    if best_perm:
        mapper = dict(zip(pred_vars, best_perm)) # make the correct mapping.
        pred_mapped = pred_expr.subs(mapper)
        
        # run simplify for a final sanity check 
        final_ratio = sympy.simplify(pred_mapped / true_expr)
        
        if final_ratio.is_constant():
            return True

    return False

In [37]:
# finally, apply the above onto the dataframe and add the col
df_merged["equivalent"] = df_merged.apply(
    lambda row: check_equality(
        row["Predicted Equation"],   # predicted
        row["Equation"]        # ground truth
    ),
    axis=1
)

[alpha, d, n]
(0, 1, 2)
[T, h, kb, omega]
[m, omega, omega_0, x]
(0, 1, 2, 3)
(0, 1, 3, 2)
(0, 2, 1, 3)
(0, 2, 3, 1)
(0, 3, 1, 2)
(0, 3, 2, 1)
(1, 0, 2, 3)
(1, 0, 3, 2)
(1, 2, 0, 3)
(1, 2, 3, 0)
(1, 3, 0, 2)
(1, 3, 2, 0)
(2, 0, 1, 3)
(2, 0, 3, 1)
(2, 1, 0, 3)
(2, 1, 3, 0)
(2, 3, 0, 1)
(2, 3, 1, 0)
(3, 0, 1, 2)
(3, 0, 2, 1)
(3, 1, 0, 2)
(3, 1, 2, 0)
(3, 2, 0, 1)
(3, 2, 1, 0)
[Ef, h, omega, omega_0, p_d, t]
[c, omega_0, v]
(0, 1, 2)
(0, 2, 1)
(1, 0, 2)
(1, 2, 0)
(2, 0, 1)
(2, 1, 0)
[B, h, mom]
(0, 1, 2)
[B, mom, theta]
[T, c, h, kb, omega]
[F, r, theta]
[Ef, m, omega, omega_0, q]
[c, epsilon, q, r, v]
[epsilon, p_d, r, theta]
[B, Jz, g_, h, mom]
[g, m, z]
(0, 1, 2)
[G, m1, m2, r1, r2]
[c, m_0, v]
[Ef, q2]
(0, 1)
[Volt, d, mu_drift, q]
(0, 1, 2, 3)
[Ef, p_d, theta]
(0, 1, 2)
[B, Ef, q, theta, v]

In [38]:
df_merged

,Equation,loss,Predicted Equation,equivalent
Filename,,,,
III.15.27,2*pi*alpha/(d*n),0.691378,7.57864633550616*alpha_var/(d_var*n_var),True
III.4.33,h*omega/(2*pi*(exp(h*omega/(2*pi*T*kb)) - 1)),0.610308,T_var*kb_var,False
I.24.6,m*x**2*(omega**2 + omega_0**2)/4,5.152108,0.51794980978129*m_var*omega_0_var*omega_var*x...,False
III.9.52,8*pi*Ef*p_d*sin(t*(omega - omega_0)/2)**2/(h*t...,161.107220,0.5495791*entropy_var/h_var,False
I.34.14,omega_0*(1 + v/c)/sqrt(1 - v**2/c**2),0.084147,omega_0_var + omega_0_var*v_var/c_var,False
III.7.38,4*pi*B*mom/h,195.228970,B_var*luminosity_var/h_var,True
II.15.4,-B*mom*cos(theta),0.004719,B_var*(-mom_var + 0.0135991452421675 - 1.14407...,False
I.41.16,h*omega**3/(2*pi**3*c**2*(exp(h*omega/(2*pi*T*...,2.591036,kb_var*omega_var/c_var**2,False
I.18.12,F*r*sin(theta),14.315337,10.269543*sin(F_var),False
II.11.3,Ef*q/(m*(-omega**2 + omega_0**2)),0.004089,Ef_var*q_var*exp(-m_var)/omega_0_var,False
II.21.32,q/(4*pi*epsilon*r*(1 - v/c)),0.002324,0.0545000844036044,False
II.6.15b,3*p_d*sin(theta)*cos(theta)/(4*pi*epsilon*r**3),0.000997,0.29548213**magnetic_flux_var,False
II.34.29b,2*pi*B*Jz*g_*mom/h,10260.426000,g__var*mom_var*temperature_var/h_var,False
I.14.3,g*m*z,0.109214,g_var*m_var*z_var,True
I.13.12,G*m1*m2*(1/r2 - 1/r1),34.244987,m1_var*(r1_var - r2_var),False
I.10.7,m_0/sqrt(1 - v**2/c**2),0.020353,1.0440441*m_0_var,False
I.12.5,Ef*q2,0.010847,Ef_var*q2_var,True
I.43.16,Volt*mu_drift*q/d,0.022459,Volt_var*mu_drift_var*q_var/d_var,True
II.15.5,-Ef*p_d*cos(theta),0.039221,-0.977359140865279*Ef_var*p_d_var*cos(theta_va...,False
I.12.11,q*(B*v*sin(theta) + Ef),108.157060,B_var*q_var*v_var*sin(theta_var),False

In [39]:
df_merged[df_merged['equivalent']==True]

,Equation,loss,Predicted Equation,equivalent
Filename,,,,
III.15.27,2*pi*alpha/(d*n),0.691378,7.57864633550616*alpha_var/(d_var*n_var),True
III.7.38,4*pi*B*mom/h,195.228970,B_var*luminosity_var/h_var,True
I.14.3,g*m*z,0.109214,g_var*m_var*z_var,True
I.12.5,Ef*q2,0.010847,Ef_var*q2_var,True
I.43.16,Volt*mu_drift*q/d,0.022459,Volt_var*mu_drift_var*q_var/d_var,True

In [40]:
df_merged.to_csv('llm_unguided_results_20_eqs')
# df_merged.to_csv('non_guided_results_20_eqs')
# score (pysr with defaults) = 46/97 (appx 47%) # took at most a minute to run
# score (pysr with added sqrt, sin, exp, cos) = 55/97 (appx 56%) ~ took about 30 minutes to run


# previous run: 9 correct equations predicted out of 20 (ran in 30 minutes) - LLM aided
# current run: 8 correct equations predicted out of 20 (ran in 7 minutes)

In [41]:
df_guided = pd.read_csv('llm_guided_results_20_eqs')
df_unguided = pd.read_csv('llm_unguided_results_20_eqs')
df_guided.set_index('Filename')
df_unguided.set_index('Filename')
x=df_guided.merge(df_unguided,on='Filename')[['Filename','Equation_x','Predicted Equation_x','loss_x', 'Predicted Equation_y','loss_y','equivalent_x','equivalent_y']]

In [42]:
# 0-1  scale the loss: do (x-min)/max-min
loss_guided = x['loss_x']
loss_unguided=x['loss_y']
loss_guided_scaled=(loss_guided-loss_guided.min())/(loss_guided.max()-loss_guided.min())
loss_unguided_scaled=(loss_unguided-loss_unguided.min())/(loss_unguided.max()-loss_unguided.min())
print('avg 0-1 scaled loss for guided: ', loss_guided_scaled.mean()  )
print('avg 0-1 scaled loss for unguided: ', loss_unguided_scaled.mean() )
print(x[(x['equivalent_x'] == True) & (x['equivalent_y'] == False)].shape[0])
print(x[(x['equivalent_x'] == False) & (x['equivalent_y'] == True)].shape[0])

avg 0-1 scaled loss for guided:  0.051891732925778145
avg 0-1 scaled loss for unguided:  0.052545595504993804
2
0